iucode_tool:
  generator: builtin-noop
  template:
    engine: helm

  defaults:
    template: ../../templates/simple.tmpl
    files_dir: "{{ .Values.pn }}"
    category: sys-apps

  packages:
    - iucode_tool:
        vars:
          versions:
            - "2.3.1"
          desc: "tool to manipulate Intel X86 and X86-64 processor microcode update collections"
          homepage: "https://gitlab.com/iucode-tool/"
          license: GPL-2
          s: '${WORKDIR}/{{ .Values.pn | replace "_" "-" }}-{{ .Values.version }}'
        assets:
          - name: '{{ .Values.pn | replace "_" "-" }}_{{ .Values.version }}.tar.xz'
            prefix: https://gitlab.com/iucode-tool/releases/raw/master/

fwupd_packages:
  generator: builtin-github

  defaults:
    template: ../../templates/simple-github.tmpl
    files_dir: "{{ .Values.pn }}"
    category: sys-apps
    vars:
      python_compat: python3+
      homepage: https://fwupd.org
    github:
      user: fwupd
      query: releases

  packages:

    - fwupd:
        vars:
          license: LGPL-2.1+
          desc: Aims to make updating firmware on Linux automatic, safe and reliable
          inherit:
            - bash-completion-r1
            - meson
            - python-single-r1
            - vala
            - udev
            - xdg
          patches:
            - elogind.patch
          iuse: |
            amdgpu amt archive bash-completion bluetooth +dell +elogind flashrom
            +gnutls gtk-doc introspection logitech lzma +man minimal modemmanager nvme
            policykit spi +sqlite synaptics thunderbolt tpm +uefi +hsi +lvfs

          required_use: |
            ^^ ( elogind minimal )
            dell? ( uefi )
            minimal? ( !introspection )
            spi? ( lzma )
            synaptics? ( gnutls )
            uefi? ( gnutls )

          bdepend: |
            $(vala_depend)
            virtual/pkgconfig
            gtk-doc? ( dev-util/gtk-doc )
            bash-completion? ( >=app-shells/bash-completion-2.0 )
            introspection? ( dev-libs/gobject-introspection )
            man? (
              app-text/docbook-sgml-utils
              sys-apps/help2man
            )

          cdepend: |
            ${PYTHON_DEPS}
            app-arch/gcab
            app-arch/xz-utils
            dev-libs/glib:2
            dev-libs/json-glib
            dev-libs/libgudev:=
            dev-libs/libjcat[gpg,pkcs7]
            dev-libs/libxmlb:=[introspection?]
            $(python_gen_cond_dep '
              dev-python/pygobject:3[cairo,${PYTHON_USEDEP}]
            ')
            net-libs/libsoup:2.4[introspection?]
            net-misc/curl
            archive? ( app-arch/libarchive:= )
            dell? ( sys-libs/libsmbios )
            elogind? ( sys-auth/elogind )
            flashrom? ( sys-apps/flashrom )
            gnutls? ( net-libs/gnutls )
            logitech? ( dev-libs/protobuf-c:= )
            lzma? ( app-arch/xz-utils )
            modemmanager? ( net-misc/modemmanager[qmi] )
            policykit? ( sys-auth/polkit )
            sqlite? ( dev-db/sqlite )
            tpm? ( app-crypt/tpm2-tss:= )
            uefi? (
              sys-apps/fwupd-efi
              sys-boot/efibootmgr
              sys-fs/udisks
              sys-libs/efivar
            )

          rdepend: |
            ${CDEPEND}
            sys-apps/dbus

          depend: |
            ${CDEPEND}
            x11-libs/pango[introspection]

          body: |
            src_prepare() {
              default
              sed -e "/install_dir.*'doc'/s/fwupd/${PF}/" \
                -i data/meson.build || die

              vala_src_prepare
            }
            src_configure() {
              local emesonargs=(
                --localstatedir "${EPREFIX}"/var
                -Dbuild="$(usex minimal standalone all)"
                -Dsystemd="disabled"
                -Ddocs="$(usex gtk-doc enabled disabled)"
                -Defi_binary="false"
                -Dsupported_build="enabled"
                $(meson_feature archive libarchive)
                $(meson_use bash-completion bash_completion)
                $(meson_feature bluetooth bluez)
                $(meson_feature elogind)
                $(meson_feature gnutls)
                $(meson_feature flashrom plugin_flashrom)
                $(meson_feature modemmanager plugin_modem_manager)
                $(meson_use uefi plugin_uefi_capsule_splash)
                $(meson_feature introspection)
                $(meson_feature policykit polkit)
                $(meson_use man)
                $(meson_use lvfs)
                $(meson_feature hsi)
                -Dtests=false
              )
              use uefi && emesonargs+=( -Defi_os_dir="macaronios" )
              export CACHE_DIRECTORY="${T}"
              meson_src_configure
            }
            src_install() {
              meson_src_install
              if ! use minimal ; then
                newinitd "${FILESDIR}"/${PN}-r2 ${PN}
                # Don't timeout when fwupd is running (#673140)
                sed '/^IdleTimeout=/s@=[[:digit:]]\+@=0@' \
                  -i "${ED}"/etc/${PN}/fwupd.conf || die
              fi
            }
            pkg_postinst() {
              xdg_pkg_postinst
              use minimal || udev_reload
            }
            pkg_postrm() {
              xdg_pkg_postrm
              use minimal || udev_reload
            }

    - fwupd-efi:
        vars:
          license: LGPL-2.1+
          desc: EFI executable for fwupd
          inherit:
            - meson
            - python-single-r1
          bdepend: |
            ${PYTHON_DEPS}
            virtual/pkgconfig
          depend: |
            sys-boot/gnu-efi
            $(python_gen_cond_dep 'dev-python/pefile[${PYTHON_USEDEP}]')
          body: |
            src_prepare() {
              default
              python_fix_shebang "${S}/efi"
            }
            src_configure() {
              local emesonargs=(
                -Defi-libdir="${EPREFIX}"/usr/$(get_libdir)
                -Defi_sbat_distro_id="macaroni"
                -Defi_sbat_distro_summary="MacaroniOS GNU/Linux"
                -Defi_sbat_distro_pkgname="${PN}"
                -Defi_sbat_distro_version="${PVR}"
              )
              meson_src_configure
            }



upower:
  generator: builtin-dirlisting
  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: sys-power
    dir:
      url: 'https://gitlab.freedesktop.org/{{ .Values.gitlab_user }}/{{ .Values.gitlab_repo }}/-/tags'
      matcher: "/{{ .Values.gitlab_user }}/{{ .Values.gitlab_repo }}/-/releases/v[0-9.]+"
      # Skip release candidate/beta versions
      exclude: '90[0-9]$'
    transform:
      - kind: string
        match: 'v'
        replace: ''
    assets:
      - name: '{{ .Values.pn }}-{{ .Values.version }}.tar.bz2'
        url: 'https://gitlab.freedesktop.org/{{ .Values.gitlab_user }}/{{ .Values.gitlab_repo }}/-/archive/{{ .Values.original_version }}/{{ .Values.pn }}-{{ .Values.version }}.tar.bz2'
    vars:
      license: GPL-2+
      python_compat: python3+
      iuse: gtk-doc +introspection policykit
      inherit:
        - meson
        - python-any-r1
        - systemd
        - udev
        - xdg-utils
      rdepend: |
        dev-libs/glib:2
        sys-apps/dbus:=
        introspection? ( dev-libs/gobject-introspection:= )
        policykit? ( sys-auth/polkit )
        dev-libs/libgudev:=
        virtual/udev
      depend: '${RDEPEND}'
      bdepend: |
        app-text/docbook-xsl-stylesheets
        dev-libs/libxslt
        dev-util/gdbus-codegen
        sys-devel/gettext
        gtk-doc? ( dev-util/gtk-doc )
      body: |
        post_src_unpack() {
          mv upower-v* "${S}"
        }
        src_prepare() {
          default
          xdg_environment_reset
          # https://bugs.gentoo.org/935575
          unset XDG_CONFIG_DIRS XDG_DATA_DIRS
        }
        src_configure() {
          local backend=linux
          local emesonargs=(
            --localstatedir "${EPREFIX}"/var
            -Dman=true
            -Dsystemdsystemunitdir="$(systemd_get_systemunitdir)"
            -Dos_backend="${backend}"
            -Didevice=disabled
            $(meson_use gtk-doc)
            $(meson_feature introspection)
            $(meson_feature policykit polkit)
          )
          meson_src_configure
        }
        src_install() {
            meson_src_install
            keepdir /var/lib/upower #383091
        }
        pkg_postinst() {
            udev_reload
        }
        pkg_postrm() {
            udev_reload
        }

  packages:
    - upower:
        vars:
          gitlab_user: upower
          gitlab_repo: upower
          desc: D-Bus abstraction for enumerating power devices, querying history and statistics
          homepage: https://upower.freedesktop.org/
