sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "core-server-kit"
  url: "https://github.com/macaroni-os/core-server-kit"
  branch: "mark-testing"

- name: "dev-kit"
  url: "https://github.com/macaroni-os/dev-kit"
  branch: "mark-testing"

- name: "lang-kit"
  url: "https://github.com/macaroni-os/lang-kit"
  branch: "mark-testing"

- name: "text-kit"
  url: "https://github.com/macaroni-os/text-kit"
  branch: "mark-testing"

- name: "security-kit"
  url: "https://github.com/macaroni-os/security-kit"
  branch: "mark-testing"

- name: "gnome-kit"
  url: "https://github.com/macaroni-os/gnome-kit"
  branch: "mark-testing"

target:
  name: dev-kit
  url: "https://github.com/macaroni-os/dev-kit"
  branch: mark-xl

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: app-text/asciidoc
    - pkg: app-text/manpager
    - pkg: app-text/opensp

    - pkg: dev-cpp/tbb

    - pkg: dev-libs/libaio
    - pkg: dev-libs/libpipeline
    - pkg: dev-libs/libuv
    - pkg: dev-libs/libxslt

    - pkg: dev-libs/lzo
    - pkg: dev-libs/jsoncpp
    - pkg: dev-libs/mpc
    - pkg: dev-libs/mpfr
    - pkg: dev-libs/nspr
    - pkg: dev-libs/nss
    - pkg: dev-libs/popt

    - pkg: dev-libs/boost

    - pkg: dev-util/b2
    - pkg: dev-util/cmake
    - pkg: dev-util/gtk-doc
    - pkg: dev-util/gperf
    - pkg: dev-util/intltool
    - pkg: dev-util/itstool
    - pkg: dev-util/yacc
    - pkg: dev-util/meson
    - pkg: dev-util/ninja
    - pkg: dev-util/re2c
    - pkg: dev-util/patchelf
    - pkg: dev-util/pkgconf

    - pkg: dev-vcs/git

    - pkg: sys-apps/busybox
    - pkg: sys-apps/help2man
    - pkg: sys-apps/man-db
    - pkg: sys-apps/man-pages
    - pkg: sys-apps/man-pages-posix

    - pkg: sys-devel/bison
    - pkg: sys-devel/flex

    - pkg: sys-libs/libseccomp

    - pkg: virtual/yacc
    - pkg: virtual/man
    - pkg: virtual/pkgconfig
