#!/bin/sh

AWG_QUICK="/usr/bin/awg-quick"

start() {
		if [ ! -f "${AWG_QUICK}" ]; then
			echo "awg-quick binary not found. Did you emerge net-vpn/amneziawg-tools?"
			exit 1
		fi
		if [ ! -f /etc/amnezia/amneziawg/${interface}.conf ]; then
			echo "Can't find /etc/amnezia/amneziawg/${interface}.conf. Please ensure this file exists."
		fi
		ebegin "Configuring amneziawg interface $interface"
		$AWG_QUICK up $interface 2>/dev/null
		eend $?
}

stop() {
		ebegin "Stopping amneziawg interface $interface"
		$AWG_QUICK down $interface 2>/dev/null
		eend $?
}
