sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "core-hw-kit"
  url: "https://github.com/macaroni-os/core-hw-kit"
  branch: "mark-testing"

- name: "net-kit"
  url: "https://github.com/macaroni-os/net-kit"
  branch: "mark-testing"

- name: "geaaru-kit"
  url: "https://github.com/geaaru/geaaru_overlay"
  branch: "funtoo"

target:
  name: core-hw-kit
  url: "https://github.com/macaroni-os/core-hw-kit"
  branch: mark-iii

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: app-admin/hddtemp

    - pkg: app-laptop/hdapsd
    - pkg: app-laptop/radeontool
    - pkg: app-laptop/tp_smapi

    - pkg: app-pda/libimobiledevice
    - pkg: app-pda/libimobiledevice-glue
    - pkg: app-pda/libplist
    - pkg: app-pda/libusbmuxd

    - pkg: app-misc/ddcutil
    - pkg: app-misc/lirc

    - pkg: dev-libs/libusb
    - pkg: dev-libs/libmodbus
    - pkg: dev-libs/libusb-compat
    - pkg: dev-libs/libwacom
    - pkg: net-wireless/b43-fwcutter
    - pkg: net-wireless/bluez
    - pkg: net-wireless/bluez-tools
    - pkg: net-wireless/bluez-hcidump
    - pkg: net-wireless/crda
    - pkg: net-wireless/irda-utils
    - pkg: net-wireless/iwd
    - pkg: net-wireless/wireless-regdb
    - pkg: sys-apps/dmapi
    - pkg: sys-apps/dmidecode
    - pkg: sys-apps/flashrom
    - pkg: sys-apps/fwupd
    - pkg: sys-apps/fwupd-efi
    - pkg: sys-apps/fxload
    - pkg: sys-apps/hwloc
    - pkg: sys-apps/i2c-tools
    - pkg: sys-apps/iucode_tool
    - pkg: sys-apps/lm_sensors
    - pkg: sys-apps/lshw
    - pkg: sys-apps/hwdata

    - pkg: sys-firmware/bluez-firmware
    - pkg: sys-firmware/edk2-ovmf-bin
    - pkg: sys-firmware/edk2-ovmf
    - pkg: sys-firmware/ipxe
    - pkg: sys-firmware/sgabios
    - pkg: sys-firmware/seabios
    - pkg: sys-firmware/seabios-bin
    - pkg: sys-firmware/vgabios

    - pkg: sys-power/iasl

    - pkg: virtual/libusb:1

