sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "core-hw-kit"
  url: "https://github.com/macaroni-os/core-hw-kit"
  branch: "mark-testing"

target:
  name: core-hw-kit
  url: "https://github.com/macaroni-os/core-hw-kit"
  branch: mark-xl

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: dev-libs/libusb

    - pkg: virtual/libusb:1
