general_github:
  generator: builtin-github
  defaults:
    template: ../../templates/simple-github.tmpl
    files_dir: '{{ .Values.pn }}'
    category: sys-fs
    github:
      query: releases

  packages:

    - fuse:
        template: ../../templates/simple.tmpl
        github:
          user: libfuse
          repo: libfuse
        assets:
          - name: '{{ .Values.pn }}-{{ .Values.version }}.tar.gz'
            matcher: '{{ .Values.pn }}-.*.tar.gz$'
        transform:
          - kind: string
            match: '{{ .Values.pn }}-'
            replace: ''
        vars:
          python_compat: python3+
          inherit:
            - flag-o-matic
            - meson
            - udev
            - python-any-r1
          slot: 3
          iuse: +suid
          bdepend: |
            virtual/pkgconfig
          rdepend: |
            sys-fs/fuse-common
          docs:
            - AUTHORS
            - ChangeLog.rst
            - README.md
            - doc/README.NFS
            - doc/kernel.txt
          body: |
            src_configure() {
              # bug #853058
              filter-lto
              local emesonargs=(
                -Dexamples=false
                -Dtests=false
                -Duseroot=false
                -Dinitscriptdir=
                -Dudevrulesdir="${EPREFIX}$(get_udevdir)/rules.d"
              )
              meson_src_configure
            }
            src_install() {
              meson_src_install
              # Installed via fuse-common
              rm -r "${ED}"{/etc,$(get_udevdir)} || die
              # useroot=false prevents the build system from doing this.
              use suid && fperms u+s /usr/bin/fusermount3
              # manually install man pages to respect compression
              rm -r "${ED}"/usr/share/man || die
              doman doc/{fusermount3.1,mount.fuse3.8}
            }


    - libostree:
        template: ../../templates/simple.tmpl
        github:
          user: ostreedev
          repo: ostree
        assets:
          - name: '{{ .Values.pn }}-{{ .Values.version }}.tar.xz'
            matcher: '{{ .Values.pn }}-.*.tar.xz$'
        vars:
          inherit:
            - autotools
            - systemd
            - tmpfiles
          iuse: |
            avahi curl dracut gnutls +gpg +http2 introspection
            doc +libmount man openssl systemd sodium +soup
          required_use: |
            || ( soup curl )
          # We force using of soup 3 for new releases.
          rdepend: |
            dev-libs/glib:2
            app-arch/xz-utils
            app-arch/libarchive
            sys-libs/zlib
            sys-fs/fuse:3=
            avahi? ( net-dns/avahi )
            curl? ( net-misc/curl )
            gnutls? ( net-libs/gnutls )
            openssl? ( dev-libs/openssl )
            sodium? ( dev-libs/libsodium )
            soup? ( net-libs/libsoup:3 )
            libmount? ( sys-apps/util-linux )
          depend: |
            ${RDEPEND}
            curl? ( net-libs/libsoup:3 )
            introspection? ( dev-libs/gobject-introspection )
            doc? ( dev-util/gtk-doc )
            man? ( dev-libs/libxslt )
          bdepend: |
            virtual/pkgconfig
            sys-fs/e2fsprogs
            sys-devel/bison
          body: |
            src_prepare() {
                default
                eautoreconf
            }
            src_configure() {
                unset YACC
                local econfargs=(
                    --enable-man
                    --enable-shared
                    --with-grub2-mkconfig-path=grub-mkconfig
                    --with-modern-grub
                    --with-libarchive
                    --without-selinux
                    $(use_with curl)
                    $(use_with dracut dracut yesbutnoconf) #816867
                    $(use_enable doc gtk-doc)
                    $(usex introspection --enable-introspection={,} yes no)
                    $(use_with gpg gpgme)
                    $(use_enable http2)
                    $(use_with soup soup3)
                    --without-soup # libsoup:2.4
                    $(use_with libmount)
                    $(use_with sodium ed25519-libsodium)
                    $(use_with systemd libsystemd)
                    $(use_with avahi)
                )
                if use systemd; then
                    econfargs+=( --with-systemdsystemunitdir="$(systemd_get_systemunitdir)" )
                fi
                # Crypto for checksums:
                # prefer gnutls over openssl if both are selected
                if use gnutls; then
                    econfargs+=( --with-crypto=gnutls )
                elif use openssl; then
                    econfargs+=( --with-crypto=openssl )
                else
                    econfargs+=( --with-crypto=glib )
                fi
                unset ${!XDG_*}
                econf "${econfargs[@]}"
            }
            src_install() {
                default
                rm -f ${D}/etc/grub.d/15_ostree
                dotmpfiles src/boot/ostree-tmpfiles.conf #901797
                find "${D}" -name '*.la' -type f -delete || die
            }
            pkg_postinst() {
                tmpfiles_process ostree-tmpfiles.conf
            }

eudev:
  generator: builtin-github
  defaults:
    category: sys-fs
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    github:
      query: releases
      user: eudev-project
    transform:
      - kind: string
        match: 'Release '
        replace: ''

    exclude:
      - 'Pre-release'
    assets:
      - name: '{{ .Values.pn }}-{{ .Values.version }}.tar.gz'

    vars:
      inherit:
        - autotools
        - toolchain-funcs
        - user
      iuse: +hwdb +kmod introspection +rule-generator static-libs
      cdepend: |
        sys-apps/util-linux
        introspection? ( dev-libs/gobject-introspection:= )
        kmod? ( sys-apps/kmod )
        !sys-apps/gentoo-systemd-integration
        !sys-apps/systemd
      depend: |
        ${CDEPEND}
        dev-util/gperf
        virtual/os-headers
        virtual/pkgconfig
        sys-devel/make
        sys-kernel/linux-headers
        dev-util/intltool
      rdepend: |
        ${CDEPEND}
        !sys-fs/udev
        !sys-apps/systemd
        !sys-fs/udev-init-scripts
      pdepend: |
        hwdb? ( sys-apps/hwids[udev] )
      body: |
        src_prepare() {
          # change rules back to group uucp instead of dialout for now
          sed -e 's/GROUP="dialout"/GROUP="uucp"/' -i rules/*.rules \
          || die "failed to change group dialout to uucp"
          # FL-9484: enable net-generator for VMware virtual interfaces:
          sed -i -e '/^# ignore VMWare/,+1d' rule_generator/75-persistent-net-generator.rules || die "fail"
          eapply_user
          eautoreconf
        }
        src_configure() {
          tc-export CC #463846
          export cc_cv_CFLAGS__flto=no #502950

          # Keep sorted by ./configure --help and only pass --disable flags
          # when *required* to avoid external deps or unnecessary compile
          local econf_args
          econf_args=(
            ac_cv_search_cap_init=
            ac_cv_header_sys_capability_h=yes
            DBUS_CFLAGS=' '
            DBUS_LIBS=' '
            --with-rootprefix=
            --with-rootrundir=/run
            --exec-prefix="${EPREFIX}"
            --bindir="${EPREFIX}"/bin
            --includedir="${EPREFIX}"/usr/include
            --libdir="${EPREFIX}"/usr/$(get_libdir)
            --with-rootlibexecdir="${EPREFIX}"/lib/udev
            --enable-split-usr
            --enable-manpages
            --disable-hwdb
            --disable-selinux
            --with-rootlibdir="${EPREFIX}"/$(get_libdir)
            $(use_enable introspection)
            $(use_enable kmod)
            $(use_enable static-libs static)
            $(use_enable rule-generator)
          )
          ECONF_SOURCE="${S}" econf "${econf_args[@]}"
        }
        src_install() {
            find "${D}" -name '*.la' -delete || die
            insinto /lib/udev/rules.d
            for x in udev udev-trigger udev-settle; do
                doinitd "${FILESDIR}"/$x
            done
            doins "${FILESDIR}"/40-macaroni.rules
            use rule-generator && doinitd "${FILESDIR}"/udev-postmount
            default
        }
        add_initd_to_runlevel() {
            if [[ ! -x "${EROOT}"/etc/init.d/${1} ]]; then
                die "${EROOT}/etc/init.d/${1} not found."
            fi
            if [[ ! -d "${EROOT}"/etc/runlevels/${2} ]]; then
                die "Runlevel ${2} not found."
            fi
            if [[ ! -L "${EROOT}/etc/runlevels/${2}/${1}" ]]; then
                ln -snf /etc/init.d/${1} "${EROOT}"/etc/runlevels/${2}/${1} || die "Couldn't add ${1} to runlevel ${2}"
                ewarn "Adding ${1} to the ${2} runlevel"
            fi
        }
        pkg_postinst() {
          # TODO: replace this with entities.
          enewgroup input
          enewgroup kvm 78
          enewgroup render
          mkdir -p "${EROOT}"run
          # "losetup -f" is confused if there is an empty /dev/loop/, Bug #338766
          # So try to remove it here (will only work if empty).
          rmdir "${EROOT}"dev/loop 2>/dev/null
          if [[ -d ${EROOT}dev/loop ]]; then
              ewarn "Please make sure your remove /dev/loop,"
              ewarn "else losetup may be confused when looking for unused devices."
          fi
          # REPLACING_VERSIONS should only ever have zero or 1 values but in case it doesn't,
          # process it as a list.  We only care about the zero case (new install) or the case where
          # the same version is being re-emerged.  If there is a second version, allow it to abort.
          local rv rvres=doitnew
          for rv in ${REPLACING_VERSIONS} ; do
              if [[ ${rvres} == doit* ]]; then
                  if [[ ${rv%-r*} == ${PV} ]]; then
                      rvres=doit
                  else
                      rvres=${rv}
                  fi
              fi
          done
          if use hwdb && has_version 'sys-apps/hwids[udev]'; then
              udevadm hwdb --update --root="${ROOT%/}"
              # https://cgit.freedesktop.org/systemd/systemd/commit/?id=1fab57c209035f7e66198343074e9cee06718bda
              # reload database after it has be rebuilt, but only if we are not upgrading
              if [[ ${rvres} == doit* ]] && [[ ${ROOT%/} == "" ]]; then
                  udevadm control --reload
              fi
          fi
          if [[ ${rvres} != doitnew ]]; then
              ewarn
              ewarn "You need to restart eudev as soon as possible to make the"
              ewarn "upgrade go into effect:"
              ewarn "\t/etc/init.d/udev --nodeps restart"
          fi
          for f in udev udev-trigger; do
              add_initd_to_runlevel $f sysinit
          done
          if use rule-generator; then
              add_initd_to_runlevel udev-postmount default
          fi
        }

  packages:
    - eudev:

