media_libs:
  generator: builtin-dirlisting
  generator_opts:
    # Limit rate at 1reqs/sec
    rate_limiter: "1"
  template:
    engine: helm

  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: media-libs
    dir:
      url: https://download.gnome.org/sources/{{ .Values.pn }}/{{ .Values.release }}/

  packages:

    - gexiv2:
        dir:
          matcher: "gexiv2-.*.tar.xz$"
        transform:
          - kind: string
            match: "gexiv2-"
            replace: ""
          - kind: string
            match: ".tar.xz"
            replace: ""
        vars:
          release: 0.14
          python_compat: python3+
          desc: GObject-based wrapper around the Exiv2 library
          homepage: https://wiki.gnome.org/Projects/gexiv2
          license: LGPL-2.1
          iuse: gtk-doc +introspection python static-libs +vala
          inherit:
            - meson
            - python-r1
            - vala
            - xdg-utils
          rdepend: |
            ${PYTHON_DEPS}
            dev-libs/glib:2
            media-gfx/exiv2:0=
            introspection? ( dev-libs/gobject-introspection:= )
          depend: |
            ${RDEPEND}
            virtual/pkgconfig
            gtk-doc? ( dev-util/gtk-doc )
          required_use: |
            python? ( introspection ${PYTHON_REQUIRED_USE} )
            vala? ( introspection )
          body: |
            src_prepare() {
              xdg_environment_reset
              use vala && vala_src_prepare
              default
            }
            src_configure() {
              local emesonargs=(
                $(meson_use introspection)
                $(meson_use vala vapi)
                $(meson_use gtk-doc gtk_doc)
                # prevents installation of python modules (uses install_data from meson
                # which does not optimize the modules
                -Dpython3=false
              )
              meson_src_configure
            }
            src_install() {
              meson_src_install
              if use python ; then
                python_moduleinto gi/overrides/
                python_foreach_impl python_domodule GExiv2.py
              fi
            }


net_misc_cat:
  generator: builtin-dirlisting
  generator_opts:
    # Limit rate at 1reqs/sec
    rate_limiter: "1"
  template:
    engine: helm

  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: net-misc
    dir:
      url: https://download.gnome.org/sources/{{ .Values.tname | default .Values.pn }}/{{ .Values.release }}/
      matcher: "{{ .Values.tname | default .Values.pn }}-.*.tar.xz$"
    transform:
      - kind: string
        match: "{{ .Values.tname | default .Values.pn }}-"
        replace: ""
      - kind: string
        match: ".tar.xz"
        replace: ""
    vars:
      s: '${WORKDIR}/{{ .Values.tname | default .Values.pn }}-{{ .Values.version }}'

  packages:
    - rygel:
        vars:
          release: "0.40"
          desc: Rygel is an open source UPnP/DLNA MediaServer
          homepage: https://wiki.gnome.org/Projects/Rygel
          license: LGPL-2.1+ CC-BY-SA-3.0 GPL-2
          inherit:
            - meson
            - systemd
            - vala
            - xdg
          iuse: X +introspection +sqlite tracker test transcode gtk-doc
          rdepend: |
            dev-libs/glib
            dev-libs/libgee:0.8
            dev-libs/libxml2:2
            media-libs/gupnp-dlna:2.0
            media-libs/gstreamer:1.0
            media-libs/gst-plugins-base:1.0
            media-libs/libmediaart:2.0
            media-plugins/gst-plugins-soup:1.0
            media-libs/gstreamer-editing-services:1.0
            net-libs/gssdp
            net-libs/gupnp
            net-libs/gupnp-av
            net-libs/libsoup:2.4
            sys-apps/util-linux
            x11-misc/shared-mime-info
            introspection? ( dev-libs/gobject-introspection:= )
            sqlite? (
              dev-db/sqlite
              dev-libs/libunistring:=
              x11-libs/gdk-pixbuf:2
            )
            tracker? ( app-misc/tracker:= )
            transcode? (
              media-libs/gst-plugins-bad:1.0
              media-plugins/gst-plugins-twolame:1.0
              media-plugins/gst-plugins-libav:1.0
            )
            X? ( x11-libs/gtk+:3 )
          depend: |
            ${RDEPEND}
            dev-util/gtk-doc-am
          bdepend: |
            $(vala_depend)
            app-text/docbook-xml-dtd:4.5
            sys-devel/gettext
            virtual/pkgconfig
          body: |
            src_prepare() {
              vala_src_prepare
              default
            }
            src_configure() {
              local emesonargs=(
                $(meson_use gtk-doc api-docs)
                -Dsystemd-user-units-dir=$(systemd_get_userunitdir)
                -Dplugins=gst-launch$(use sqlite && echo ",lms,media-export")$(use tracker && echo ",tracker3")
                -Dengines=gstreamer
                -Dexamples=false
                $(meson_use test tests)
                $(meson_feature X gtk)
                $(meson_feature introspection)
              )
              meson_src_configure
            }


    - vala:
        category: dev-lang
        vars:
          inherit:
            - autotools
            - gnome3
          release: "0.56"
          desc: Compiler for the GObject type system
          homepage: https://wiki.gnome.org/Projects/Vala
          license: LGPL-2.1+
          rdepend: |
            dev-libs/glib
            >=dev-libs/vala-common-{{ .Values.version }}
            media-gfx/graphviz
            dev-libs/gobject-introspection:=
          depend: |
            ${RDEPEND}
            dev-libs/libxslt
            sys-devel/flex
          bdepend: |
            virtual/pkgconfig
            virtual/yacc
          body: |
            src_configure() {
                # weasyprint enables generation of PDF from HTML
                gnome3_src_configure \
                    --disable-unversioned \
                    VALAC=: \
                    WEASYPRINT=:
            }
            src_install() {
                default
                find "${D}" -name "*.la" -delete || die
            }

    - vala-common:
        category: dev-libs
        vars:
          release: "0.56"
          tname: vala
          desc: Build infrastructure for packages that use Vala
          homepage: https://wiki.gnome.org/Projects/Vala
          license: LGPL-2.1+
          body: |
            src_configure() { :; }
            src_compile() { :; }
            src_install() {
                insinto /usr/share/aclocal
                doins vala.m4 vapigen/vapigen.m4
                insinto /usr/share/vala
                doins vapigen/Makefile.vapigen
            }


mail_apps:
  generator: builtin-dirlisting
  generator_opts:
    # Limit rate at 1reqs/sec
    rate_limiter: "1"

  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: mail-client
    dir:
      url: https://download.gnome.org/sources/{{ .Values.pn }}/{{ .Values.release }}/

  packages:
    - geary:
        dir:
          matcher: "geary-.*.tar.xz$"
        transform:
          - kind: string
            match: "geary-"
            replace: ""
          - kind: string
            match: ".tar.xz"
            replace: ""
        vars:
          patches:
            - geary_30105fd4c210c8ba4e875ab003cd393064ded894.patch
          release: "3.36"
          desc: A lightweight, easy-to-use, feature-rich email client
          homepage: https://wiki.gnome.org/Apps/Geary
          license: LGPL-2.1
          inherit:
            - gnome3
            - vala
            - meson
          iuse: nls
          cdepend: |
            app-crypt/gcr:0=[gtk,introspection]
            app-crypt/libsecret
            app-text/iso-codes
            dev-db/sqlite:3
            dev-libs/glib:2[dbus]
            dev-libs/libgee:0.8=
            dev-libs/appstream-glib:0
            net-libs/gnome-online-accounts
            app-text/enchant
            dev-libs/folks:0
            dev-libs/json-glib
            dev-libs/libxml2:2
            dev-libs/gmime:3.0[vala]
            dev-libs/libpeas
            media-libs/libcanberra
            net-libs/webkit-gtk:4=[introspection]
            x11-libs/gtk+:3[introspection]
            x11-libs/libnotify
            sys-libs/libunwind
            net-mail/ytnef
            app-text/gspell[introspection,vala]
          rdepend: |
            ${CDEPEND}
            gnome-base/gsettings-desktop-schemas
            gnome-base/dconf
            nls? ( virtual/libintl )
          depend: |
            ${CDEPEND}
            app-text/gnome-doc-utils
            dev-util/desktop-file-utils
            nls? ( sys-devel/gettext )
            $(vala_depend)
            virtual/pkgconfig
          body: |
            src_prepare() {
              local i
              if use nls ; then
                if [[ -n "${LINGUAS+x}" ]] ; then
                  for i in $(cd po ; echo *.po) ; do
                    if ! has ${i%.po} ${LINGUAS} ; then
                      sed -i -e "/^${i%.po}$/d" po/LINGUAS || die
                    fi
                  done
                fi
              else
                sed -i -e 's#add_subdirectory(po)##' CMakeLists.txt || die
              fi
              gnome3_src_prepare
              vala_src_prepare
            }
            pkg_postinst() {
              gnome3_pkg_postinst
              gnome3_schemas_update
            }

extra_apps:
  generator: builtin-dirlisting
  generator_opts:
    # Limit rate at 1reqs/sec
    rate_limiter: "1"

  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: gnome-extra
    dir:
      url: https://download.gnome.org/sources/{{ .Values.pn }}/{{ .Values.release }}/

  packages:
    - gnome-weather:
        dir:
          matcher: "gnome-weather-.*.tar.xz$"
        transform:
          - kind: string
            match: "gnome-weather-"
            replace: ""
          - kind: string
            match: ".tar.xz"
            replace: ""
        vars:
          patches:
            - gnome-weather-timezone.patch
          release: "3.36"
          desc: A weather application for GNOME
          homepage: https://wiki.gnome.org/Design/Apps/Weather
          license: GPL-2+ LGPL-2+ MIT CC-BY-3.0 CC-BY-SA-3.0
          python_compat: python3+
          inherit:
            - gnome3
            - python-any-r1
            - virtualx
            - meson
          rdepend: |
            app-misc/geoclue:2.0
            dev-libs/gjs
            dev-libs/glib:2
            dev-libs/gobject-introspection:=
            dev-libs/libgweather:=
            gnome-base/gsettings-desktop-schemas
            x11-libs/gtk+:3
          depend: |
            ${RDEPEND}
            dev-libs/appstream-glib
            dev-util/intltool
            virtual/pkgconfig
          body: |
            src_prepare() {
              sed -i -e "/'appdata'\,/d" data/meson.build
              gnome3_src_prepare
            }



