sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "python-kit"
  url: "https://github.com/macaroni-os/python-kit"
  branch: "mark-testing"

- name: "python-modules-kit"
  url: "https://github.com/macaroni-os/python-modules-kit"
  branch: "mark-testing"

- name: "dev-kit"
  url: "https://github.com/macaroni-os/dev-kit"
  branch: "mark-testing"


target:
  name: python-modules-kit
  url: "https://github.com/macaroni-os/python-modules-kit"
  branch: mark-xl

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: dev-cpp/pystring

    - pkg: dev-python/libxml2-python
    - pkg: dev-python/pyelftools
    - pkg: dev-python/setuptools

    - pkg: dev-python/aiofiles
    - pkg: dev-python/async_timeout
    - pkg: dev-python/chardet
    - pkg: dev-python/charset_normalizer
    - pkg: dev-python/commonmark
    - pkg: dev-python/cryptography
    - pkg: dev-python/docker-py

    - pkg: dev-python/Babel
    - pkg: dev-python/PySocks
    - pkg: dev-python/alabaster
    - pkg: dev-python/appi
    - pkg: dev-python/boolean-py
    - pkg: dev-python/calver

    - pkg: dev-python/docutils
    - pkg: dev-python/editables

    - pkg: dev-python/idna
    - pkg: dev-python/imagesize
    - pkg: dev-python/importlib_metadata
    - pkg: dev-python/installer
    - pkg: dev-python/ipaddress
    - pkg: dev-python/jinja
    - pkg: dev-python/license-expression
    - pkg: dev-python/markupsafe
    - pkg: dev-python/meson-python
    - pkg: dev-python/mwparserfromhell
    - pkg: dev-python/namespace-sphinxcontrib
    - pkg: dev-python/pathspec
    - pkg: dev-python/pip
    - pkg: dev-python/pluggy
    - pkg: dev-python/ply
    - pkg: dev-python/pycparser
    - pkg: dev-python/pygments
    - pkg: dev-python/pyopenssl
    - pkg: dev-python/pyparsing
    - pkg: dev-python/pyproject-metadata
    - pkg: dev-python/pytz
    - pkg: dev-python/requests
    - pkg: dev-python/six
    - pkg: dev-python/snowballstemmer
    - pkg: dev-python/sphinx
    - pkg: dev-python/sphinx_rtd_theme
    - pkg: dev-python/sphinxcontrib-applehelp
    - pkg: dev-python/sphinxcontrib-devhelp
    - pkg: dev-python/sphinxcontrib-htmlhelp
    - pkg: dev-python/sphinxcontrib-jquery
    - pkg: dev-python/sphinxcontrib-jsmath
    - pkg: dev-python/sphinxcontrib-qthelp
    - pkg: dev-python/sphinxcontrib-serializinghtml
    - pkg: dev-python/toml
    - pkg: dev-python/tomli
    - pkg: dev-python/tomli-w
    - pkg: dev-python/trove-classifiers
    - pkg: dev-python/typing-extensions
    - pkg: dev-python/urllib3
    - pkg: dev-python/wheel
    - pkg: dev-python/zipp

    # Packages for build
    - pkg: dev-python/flit_core
    - pkg: dev-python/gpep517
    - pkg: dev-python/hatchling
    - pkg: dev-python/packaging
    - pkg: dev-python/packaging-legacy
    - pkg: dev-python/pdm-backend
    - pkg: dev-python/pdm-pep517
    - pkg: dev-python/setuptools-rust
    - pkg: dev-python/setuptools_scm
    - pkg: dev-python/pyrfc3339
    - pkg: dev-python/python-xlib
    - pkg: dev-python/semantic_version
    - pkg: dev-python/webcolors

    - pkg: dev-python/cython

    - pkg: virtual/python-enum34
    - pkg: virtual/python-ipaddress
