sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "python-kit"
  url: "https://github.com/macaroni-os/python-kit"
  branch: "mark-testing"

- name: "python-modules-kit"
  url: "https://github.com/macaroni-os/python-modules-kit"
  branch: "mark-testing"

- name: "dev-kit"
  url: "https://github.com/macaroni-os/dev-kit"
  branch: "mark-testing"


target:
  name: python-modules-kit
  url: "https://github.com/macaroni-os/python-modules-kit"
  branch: mark-xl

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: dev-cpp/pystring

    - pkg: dev-python/libxml2-python
    - pkg: dev-python/pyelftools
    - pkg: dev-python/setuptools

    - pkg: dev-python/aiofiles
    - pkg: dev-python/async_timeout
    - pkg: dev-python/docker-py

    # Packages for build
    - pkg: dev-python/hatchling
    - pkg: dev-python/packaging
    - pkg: dev-python/packaging-legacy
    - pkg: dev-python/pdm-backend
    - pkg: dev-python/setuptools_scm

    - pkg: dev-python/pyrfc3339
    - pkg: dev-python/python-xlib
    - pkg: dev-python/semantic_version
    - pkg: dev-python/webcolors
