sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-iii"

- name: "core-testing-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "gnome-kit"
  url: "https://github.com/macaroni-os/gnome-kit"
  branch: "mark-testing"

- name: "dev-kit"
  url: "https://github.com/macaroni-os/dev-kit"
  branch: "mark-testing"

- name: "python-modules-kit"
  url: "https://github.com/macaroni-os/python-modules-kit"
  branch: "mark-testing"

- name: "geaaru-kit"
  url: "https://github.com/geaaru/geaaru_overlay"
  branch: "funtoo"

- name: "desktop-kit"
  url: "https://github.com/macaroni-os/desktop-kit"
  branch: "mark-testing"

target:
  name: gnome-kit
  url: "https://github.com/macaroni-os/gnome-kit"
  branch: mark-unstable

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    # Deprecated libraries.
    # amtk is been replaced by libgedit-amtk
    #- pkg: x11-libs/amtk

    - pkg: app-accessibility/brltty
    # caribou is been archived
    #- pkg: app-accessibility/caribou
    - pkg: app-accessibility/orca

    # tracker is been replaced by tinysparql
    #- pkg: app-misc/tracker
    # tracker-miners is been replaced by localsearch
    #- pkg: app-misc/tracker-miners

    - pkg: dev-libs/gmime:3.0
    - pkg: dev-libs/gom
    - pkg: dev-libs/libcroco
    - pkg: dev-libs/newt
    - pkg: dev-util/gi-docgen

    - pkg: gui-libs/gtk-layer-shell
    # tepl seems deprecated with libgedit-tepl
    #- pkg: gui-libs/tepl

    - pkg: net-im/telepathy-logger
    - pkg: net-im/telepathy-mission-control

    # old packages. check if we can remove them.
    - pkg: net-libs/gssdp:0
    - pkg: net-libs/gssdp:1.2
    - pkg: net-libs/gupnp:0
    - pkg: net-libs/gupnp:1.2

    - pkg: net-libs/gtk-vnc
    # package libgfbgraph archived on upstream
    #- pkg: net-libs/libgfbgraph
    # package libzapojit archived on upstream
    #- pkg: net-libs/libzapojit
    - pkg: net-libs/telepathy-glib

    - pkg: net-misc/connman-gtk
    - pkg: net-misc/connman-ui
    # package gnome-online-miners archived on upstream
    #- pkg: net-misc/gnome-online-miners
    - pkg: net-misc/vinagre
    - pkg: net-misc/vino

    - pkg: net-wireless/blueberry

    # Ebuild already updated but to autogen
    - pkg: gnome-base/gnome-common
    - pkg: gnome-base/libglade
    - pkg: gnome-base/libgnomecanvas
    - pkg: gnome-base/gconf

    - pkg: gnome-base/adrien-gdm-keyboard

    # Packages replaced by sets
    #- pkg: gnome-base/gnome
    #- pkg: gnome-base/gnome-core-apps
    #- pkg: gnome-base/gnome-core-libs

    # gnome-shell-common is a deprecated package
    # - pkg: gnome-base/gnome-shell-common
    - pkg: gnome-base/libgnome-keyring

    # chrome-gnome-shell replaced by gnome-browser-connector
    #- pkg: gnome-extra/chrome-gnome-shell
    - pkg: gnome-extra/gconf-editor
    # gnome-documents replaced by papers
    #- pkg: gnome-extra/gnome-documents
    - pkg: gnome-extra/gnome-getting-started-docs
    - pkg: gnome-extra/gnome-integration-spotify

    # gnome-recipes and gnome-search-tool are obsoleted
    #- pkg: gnome-extra/gnome-recipes
    #- pkg: gnome-extra/gnome-search-tool

    - pkg: gnome-extra/gnome-shell-extension-applications-overview-tooltip
    - pkg: gnome-extra/gnome-shell-extension-compiz-windows-effect
    - pkg: gnome-extra/gnome-shell-extension-dash-to-dock
    - pkg: gnome-extra/gnome-shell-extension-desktop-icons
    - pkg: gnome-extra/gnome-shell-extension-dynamic-panel-transparency
    - pkg: gnome-extra/gnome-shell-extensions-topicons
    - pkg: gnome-extra/gnome-shell-extensions-topicons-plus
    - pkg: gnome-extra/gnome-shell-frippery

    # gnome-todo is been renamed in endeavour
    #- pkg: gnome-extra/gnome-todo
    - pkg: gnome-extra/gnome-user-docs
    - pkg: gnome-extra/gnome-user-share
    # nautilus-sendto is been archived. Candidate for removal?
    #- pkg: gnome-extra/nautilus-sendto
    # no updates. package to autogen
    - pkg: gnome-extra/polkit-gnome

    - pkg: games-board/aisleriot
    - pkg: games-board/gnuchess
    # obsoleted and dead package available only through web.archive.org
    - pkg: games-board/crafty

    - pkg: games-board/sjeng
    - pkg: games-board/stockfish

    - pkg: media-libs/clutter
    - pkg: media-libs/clutter-gst
    - pkg: media-libs/clutter-gtk
    - pkg: media-libs/cogl

    # upstream repository archived.
    # gnome-shell supply native screenshot feature.
    #- pkg: media-gfx/gnome-screenshot

    - pkg: x11-libs/goffice

    - pkg: x11-terms/tilix-bin

    - pkg: x11-themes/funtoo-gnome-shell-theme
    - pkg: x11-themes/gnome-icon-theme-extras
    - pkg: x11-themes/gnome-orchis-theme
    - pkg: x11-themes/gnome-themes-standard
    - pkg: x11-themes/gtk-engines
    - pkg: x11-themes/gtk-engines-adwaita
    - pkg: x11-themes/gtk-engines-murrine
