sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "science-kit"
  url: "https://github.com/macaroni-os/science-kit"
  branch: "mark-testing"

target:
  name: science-kit
  url: "https://github.com/macaroni-os/science-kit"
  branch: mark-unstable

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: sci-libs/blas-reference
    - pkg: sci-libs/cblas-reference
    - pkg: sci-libs/lapack-reference
    - pkg: sci-libs/libcerf

    - pkg: sci-visualization/gnuplot

    - pkg: virtual/blas
    - pkg: virtual/cblas
    - pkg: virtual/lapack

    - pkg: media-libs/qhull
    - pkg: sci-libs/colamd
    - pkg: sci-libs/dcmtk
    - pkg: sci-libs/djbfft
    - pkg: sci-libs/fftw
    - pkg: sci-libs/gsl
    - pkg: sci-libs/hdf5
    - pkg: sci-libs/libqalculate
    - pkg: sci-libs/suitesparseconfig
    - pkg: sci-mathematics/lpsolve
    - pkg: sci-mathematics/z3
