sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-iii"

- name: "llvm-kit"
  url: "https://github.com/macaroni-os/llvm-kit"
  branch: "mark-unstable"

target:
  name: llvm-kit
  url: "https://github.com/macaroni-os/llvm-kit"
  branch: mark-iii

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: dev-python/clang-python
      conditions:
        - '>=dev-python/clang-python-16.0.0'
        - '<dev-python/clang-python-17.0.0'

    - pkg: dev-python/clang-python
      conditions:
        - '>=dev-python/clang-python-20.0.0'
        - '<dev-python/clang-python-21.0.0'

    - pkg: sys-devel/clang-common
      conditions:
        - '>=sys-devel/clang-common-16.0.0'
        - '<sys-devel/clang-common-17.0.0'

    - pkg: sys-devel/clang-common
      conditions:
        - '>=sys-devel/clang-common-20.0.0'
        - '<sys-devel/clang-common-21.0.0'

    - pkg: sys-devel/llvm-common

    - pkg: dev-libs/libclc
    - pkg: sys-libs/libcxxabi
    - pkg: sys-libs/libcxx
    - pkg: sys-libs/libomp


    # LLVM 16 packages
    - pkg: dev-util/spirv-llvm-translator:16
    - pkg: dev-util/spriv-headers:16
      conditions:
        - '<dev-util/spriv-headers-17.0:16'

    - pkg: sys-devel/clang:16
    - pkg: sys-devel/clang-runtime:16

    - pkg: sys-devel/lld:16
    - pkg: sys-devel/llvm:16
    - pkg: sys-devel/llvmgold:16

    - pkg: sys-libs/compiler-rt:16
    - pkg: sys-libs/compiler-rt-sanitizers:16

    # LLVM 20
    - pkg: dev-util/lldb:20
    - pkg: dev-util/spirv-llvm-translator:20
    - pkg: dev-util/spriv-headers:20
      conditions:
        - '>=dev-util/spriv-headers-20.0:20'

    - pkg: sys-devel/clang:20
    - pkg: sys-devel/clang-runtime:20

    - pkg: sys-devel/lld:20
    - pkg: sys-devel/llvm:20
    - pkg: sys-devel/llvmgold:20

    - pkg: sys-libs/compiler-rt:20
    - pkg: sys-libs/compiler-rt-sanitizers:20
