sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-xl"

- name: "llvm-kit"
  url: "https://github.com/macaroni-os/llvm-kit"
  branch: "mark-xl"

target:
  name: llvm-kit
  url: "https://github.com/macaroni-os/llvm-kit"
  branch: mark-v

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

      - dir: ../../.github/workflows
        to: .github/workflows

      - file: ../../.goreleaser.yml
        to: .goreleaser.yml

  atoms_defaults:
    max_versions: 3

  atoms:
    - pkg: dev-python/clang-python

    - pkg: dev-libs/libclc

    - pkg: dev-util/lldb:16

    - pkg: sys-libs/compiler-rt:16
    - pkg: sys-libs/compiler-rt-sanitizers:16

    - pkg: sys-devel/clang-common
    - pkg: sys-devel/clang:16
    - pkg: sys-devel/clang-runtime:16

    - pkg: sys-devel/lld:16
    - pkg: sys-devel/llvm:16
    - pkg: sys-devel/llvmgold:16
    - pkg: sys-devel/llvm-common

    - pkg: sys-libs/libcxx
    - pkg: sys-libs/libcxxabi
    - pkg: sys-libs/libomp


    # LLVM 20
    - pkg: sys-devel/lld:20
    - pkg: sys-devel/llvm:20
    - pkg: sys-devel/llvmgold:20

    - pkg: sys-devel/clang:20
    - pkg: sys-devel/clang-runtime:20

    - pkg: dev-util/lldb:20
    - pkg: dev-util/spirv-llvm-translator:20
    - pkg: dev-util/spirv-headers

    - pkg: sys-libs/compiler-rt:20
    - pkg: sys-libs/compiler-rt-sanitizers:20
