sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "python-kit"
  url: "https://github.com/macaroni-os/python-kit"
  branch: "mark-testing"

- name: "security-kit"
  url: "https://github.com/macaroni-os/security-kit"
  branch: "mark-testing"

- name: "gnome-kit"
  url: "https://github.com/macaroni-os/gnome-kit"
  branch: "mark-testing"

- name: "net-kit"
  url: "https://github.com/macaroni-os/net-kit"
  branch: "mark-testing"

- name: "dev-kit"
  url: "https://github.com/macaroni-os/dev-kit"
  branch: "mark-testing"

target:
  name: security-kit
  url: "https://github.com/macaroni-os/security-kit"
  branch: mark-unstable

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml
  atoms_defaults:
    max_versions: 3

  atoms:
    - pkg: app-admin/makepasswd
    - pkg: app-admin/pwgen
    - pkg: app-admin/sshguard

    - pkg: app-antivirus/lkrg

    - pkg: app-crypt/argon2
    - pkg: app-crypt/gcr
    - pkg: app-crypt/gpgme:1
    - pkg: app-crypt/gnupg
    - pkg: app-crypt/libb2
    - pkg: app-crypt/libmd
    - pkg: app-crypt/libsecret
    - pkg: app-crypt/paperkey
    - pkg: app-crypt/p11-kit
    - pkg: app-crypt/pinentry
    - pkg: app-crypt/rhash
    - pkg: app-crypt/mhash
    - pkg: app-crypt/mit-krb5
    - pkg: app-crypt/trousers
    - pkg: app-crypt/tpm2-abrmd
    - pkg: app-crypt/tpm2-tools
    - pkg: app-crypt/tpm2-totp
    - pkg: app-crypt/tpm2-tss
    - pkg: app-crypt/tpm2-tss-engine
    - pkg: app-crypt/sbsigntools

    - pkg: app-misc/pax-utils

    - pkg: dev-libs/cyrus-sasl:2
    - pkg: dev-libs/libassuan
    - pkg: dev-libs/libgcrypt
    - pkg: dev-libs/libgpg-error
    - pkg: dev-libs/libksba
    - pkg: dev-libs/libtasn1
    - pkg: dev-libs/libunistring
    - pkg: dev-libs/libpwquality
    - pkg: dev-libs/libmcrypt
    - pkg: dev-libs/xmlsec
    - pkg: dev-libs/nettle
    - pkg: dev-libs/npth
    - pkg: dev-libs/crypto++

    - pkg: dev-libs/pkcs11-helper

    - pkg: net-libs/libgsasl
    - pkg: net-libs/liboauth
    - pkg: net-libs/mbedtls
    - pkg: net-libs/gnutls

    - pkg: net-proxy/privoxy
    - pkg: net-proxy/torsocks

    - pkg: sys-apps/keyutils
    - pkg: sys-apps/bolt
    - pkg: sys-apps/bubblewrap

    - pkg: sys-auth/elogind
    - pkg: sys-auth/pambase
    # 0.120 is masked atm.
    - pkg: sys-auth/polkit
      conditions:
        - '<sys-auth/polkit-0.120'
    - pkg: sys-auth/rtkit
    - pkg: sys-auth/google-authenticator

    - pkg: sys-boot/mokutil

    - pkg: sys-libs/pam
    - pkg: sys-libs/cracklib
    - pkg: sys-libs/libapparmor
    - pkg: sys-libs/libxcrypt

    - pkg: sys-process/audit

    - pkg: virtual/gsasl
    - pkg: virtual/krb5
    - pkg: virtual/pam
    - pkg: virtual/ssh
