net-im_github:
  generator: builtin-github
  defaults:
    template: ../../templates/simple.tmpl
    files_dir: '{{ .Values.pn }}'
    category: net-im
    github:
      query: releases

  packages:
    - mattermost-desktop-bin:
        github:
          user: mattermost
          repo: desktop
        transform:
          - kind: regex
            match: " [(].*"
            replace: ""
        assets:
          - name: '{{ .Values.pn | replace "-bin" "" }}-{{ .Values.version }}.linux-x64.tar.gz'
            matcher: '{{ .Values.pn | replace "-bin" "" }}-{{ .Values.version }}.linux-x64.tar.gz$'
            use: amd64

          - name: '{{ .Values.pn | replace "-bin" "" }}-{{ .Values.version }}.linux-arm64.tar.gz'
            matcher: '{{ .Values.pn | replace "-bin" "" }}-{{ .Values.version }}.linux-arm64.tar.gz$'
            use: arm64
        vars:
          homepage: https://mattermost.com/
          desc: Mattermost Desktop application
          license: Apache-2.0 GPL-2+ LGPL-2.1+ MIT
          inherit:
            - desktop
            - xdg
          rdepend: |
            app-accessibility/at-spi2-core[X]
            dev-libs/expat
            dev-libs/glib:2
            dev-libs/nspr
            dev-libs/nss
            dev-libs/wayland
            media-libs/alsa-lib
            media-libs/mesa
            net-print/cups
            sys-apps/dbus
            sys-libs/glibc
            x11-libs/cairo
            x11-libs/gtk+:3[X]
            x11-libs/libX11
            x11-libs/libXcomposite
            x11-libs/libXdamage
            x11-libs/libXext
            x11-libs/libXfixes
            x11-libs/libXrandr
            x11-libs/libdrm
            x11-libs/libxcb
            x11-libs/libxkbcommon
            x11-libs/pango
          docs:
            - NOTICE.txt
          s: '${WORKDIR}'
          extra_envs:
            - |
              QA_PREBUILT="
                opt/mattermost-desktop/mattermost-desktop
                opt/mattermost-desktop/libnode.so
                opt/mattermost-desktop/libffmpeg.so
                opt/mattermost-desktop/libGLESv2.so
                opt/mattermost-desktop/libEGL.so
                opt/mattermost-desktop/libvk_swiftshader.so
                opt/mattermost-desktop/libvulkan.so.1
                opt/mattermost-desktop/resources/*
              "

          body: |
            src_install() {
              local MY_PN="{{ .Values.pn | replace "-bin" "" }}"
              if use amd64; then
                cd mattermost-desktop-*-linux-x64 || die
              elif use arm64; then
                cd mattermost-desktop-*-linux-arm64 || die
              fi
              newicon app_icon.png ${MY_PN}.png
              insinto "/opt/${MY_PN}/locales"
              doins locales/*.pak
              insinto "/opt/${MY_PN}/resources"
              doins -r resources/*.asar*
              insinto "/opt/${MY_PN}"
              doins *.pak *.bin *.dat
              exeinto "/opt/${MY_PN}"
              doexe *.so *.so.* "${MY_PN}"
              dosym "/opt/${MY_PN}/${MY_PN}" "/usr/bin/${MY_PN}"
              make_desktop_entry "${MY_PN}" Mattermost "${MY_PN}"
              einstalldocs
            }

    - telegram-desktop-bin:
        github:
          user: telegramdesktop
          repo: tdesktop
        transform:
          - kind: string
            match: "v "
            replace: ""
        assets:
          - name: '{{ .Values.pn | replace "-bin" "" }}-tdesktop-{{ .Values.version }}.tar.gz'
            matcher: 'tdesktop-{{ .Values.version }}-full.tar.gz$'
            use: amd64

          - name: '{{ .Values.pn | replace "-bin" "" }}-tsetup-{{ .Values.version }}.tar.xz'
            matcher: 'tsetup.{{ .Values.version }}.tar.xz$'
            use: amd64
        vars:
          desc: Official desktop client for Telegram (binary package)
          homepage: https://desktop.telegram.org
          license: GPL-3-with-openssl-exception
          iuse: amd64
          extra_envs:
            - 'QA_PREBUILT="usr/lib/${PN}/Telegram"'
          rdepend: |
            dev-libs/glib
            dev-libs/gobject-introspection
            media-libs/fontconfig
            sys-apps/dbus
            x11-libs/libX11
            x11-libs/libxcb[xkb]
          s: '${WORKDIR}/Telegram'
          inherit:
            - desktop
            - eutils
            - xdg
          body: |
            src_install() {
              local SOURCE_DIR="${WORKDIR}/tdesktop-${PV}-full"
              exeinto /usr/lib/${PN}
              doexe "Telegram"
              newbin "${FILESDIR}"/${PN} "telegram-desktop"
              local icon_size
              for icon_size in 16 32 128 256 512; do
                newicon -s "${icon_size}" \
                  "${SOURCE_DIR}/Telegram/Telegram/Images.xcassets/Icon.iconset/icon_${icon_size}x${icon_size}.png" \
                  telegram.png
              done
              sed -i \
              -e '/SingleMainWindow=true/d' \
              -e '/DBusActivatable=true/d' \
              "${SOURCE_DIR}"/lib/xdg/org.telegram.desktop.desktop
              domenu "${SOURCE_DIR}"/lib/xdg/org.telegram.desktop.desktop
            }
            pkg_postinst() {
              xdg_pkg_postinst
            }


discord:
  generator: custom
  generator_opts:
    script: ./custom-generators/discord.sh
    enable_set_version: "false"
  defaults:
    template: ../../templates/simple.tmpl
    files_dir: '{{ .Values.pn }}'
    category: net-im

  packages:
    - discord-bin:
        assets:
          - name: '{{ .Values.pn | replace "-bin" "" }}-{{ .Values.version }}.deb'
            url: 'https://stable.dl2.discordapp.net/apps/linux/{{ .Values.version }}/discord-{{ .Values.version }}.deb'
            use: amd64
        tarball: '{{ .Values.pn | replace "-bin" "" }}-{{ .Values.version }}.deb'
        vars:
          desc: All-in-one voice and text chat for gamers
          homepage: https://discordapp.com
          license: all-rights-reserved
          iuse: amd64
          s: '${WORKDIR}'
          extra_envs:
            - 'QA_PREBUILT="/opt/discord/*"'
          inherit:
            - desktop
            - gnome3
            - pax-utils
            - unpacker
          rdepend: |
            dev-libs/atk
            dev-libs/expat
            dev-libs/glib:2
            dev-libs/nspr
            dev-libs/nss
            media-libs/alsa-lib
            media-libs/fontconfig:1.0
            media-libs/freetype:2
            net-print/cups
            sys-apps/dbus
            sys-libs/libcxx
            x11-libs/cairo
            x11-libs/gdk-pixbuf:2
            x11-libs/gtk+:3
            x11-libs/libX11
            x11-libs/libXScrnSaver
            x11-libs/libxcb
            x11-libs/libXcomposite
            x11-libs/libXcursor
            x11-libs/libXdamage
            x11-libs/libXext
            x11-libs/libXfixes
            x11-libs/libXi
            x11-libs/libXrandr
            x11-libs/libXrender
            x11-libs/libXtst
            x11-libs/libxkbcommon
            x11-libs/pango
          body: |
            src_prepare() {
              default

              sed -i \
                -e "s:/usr/share/discord/Discord.*:/opt/discord/Discord:g" \
                -e "s:discord:discord:g" \
                usr/share/discord/discord.desktop || die
              install -d "${S}/opt"
              mv -v "${S}/usr/share/discord" "${S}/opt/discord" || die
              rm -v "${S}/usr/bin/discord"
            }
            src_configure() {
              :
            }
            src_install() {
              doicon opt/discord/discord.png
              domenu opt/discord/discord.desktop
              insinto /opt/discord
              doins -r opt/discord/.
              fperms +x /opt/discord/Discord
              fperms 4755 /opt/discord/chrome-sandbox || die
              if [ -f "${ED%/}"/opt/discord/chrome_crashpad_handler ]; then
                fperms 4755 /opt/discord/chrome_crashpad_handler || die
              fi
              dosym ../../opt/discord/Discord usr/bin/discord
              pax-mark -m "${ED%/}"/opt/discord/discord
            }


slack:
  generator: custom
  generator_opts:
    script: ./custom-generators/slack.sh
    enable_set_version: "false"
  defaults:
    template: ../../templates/simple.tmpl
    files_dir: '{{ .Values.pn }}'

  packages:
    - slack-bin:
        category: net-im
        assets:
          - name: slack-desktop-{{ .Values.version }}-amd64.deb
            url: https://downloads.slack-edge.com/desktop-releases/linux/x64/{{ .Values.version }}/slack-desktop-{{ .Values.version }}-amd64.deb
            use: amd64
        vars:
          desc: Team collaboration tool
          homepage: http://www.slack.com/
          license: all-rights-reserved
          iuse: amd64 ayatana gnome-keyring pax_kernel
          inherit:
            - desktop
            - gnome3
            - pax-utils
            - unpacker
          rdepend: |
            dev-libs/atk
            dev-libs/expat
            dev-libs/glib
            dev-libs/nspr
            dev-libs/nss
            gnome-base/gconf
            media-libs/alsa-lib
            media-libs/fontconfig
            media-libs/freetype
            net-misc/curl
            net-print/cups
            sys-apps/dbus
            x11-libs/cairo
            x11-libs/gdk-pixbuf
            x11-libs/gtk+:3
            x11-libs/libX11
            x11-libs/libxcb
            x11-libs/libXcomposite
            x11-libs/libXcursor
            x11-libs/libXdamage
            x11-libs/libXext
            x11-libs/libXfixes
            x11-libs/libXi
            x11-libs/libxkbfile
            x11-libs/libXrandr
            x11-libs/libXrender
            x11-libs/libXScrnSaver
            x11-libs/libXtst
            x11-libs/pango
            ayatana? ( dev-libs/libappindicator )
            gnome-keyring? ( app-crypt/libsecret )
          extra_envs:
            - 'QA_PREBUILT="/opt/slack/*"'
          s: '${WORKDIR}'
          body: |
            src_prepare() {
              default
              if use ayatana ; then
                sed -i '/Exec/s|=|=env XDG_CURRENT_DESKTOP=Unity |' \
                  usr/share/applications/slack.desktop \
                  || die "sed failed for slack.desktop"
              fi
            }
            src_configure() {
              :
            }
            src_install() {
              doicon usr/share/pixmaps/slack.png
              doicon -s 512 usr/share/pixmaps/slack.png
              domenu usr/share/applications/slack.desktop

              insinto /opt/slack
              doins -r usr/lib/slack/.
              fperms +x /opt/slack/slack
              fperms +x /opt/slack/chrome_crashpad_handler
              fperms 4711 /opt/slack/chrome-sandbox
              dosym ../../opt/slack/slack usr/bin/slack

              use pax_kernel && pax-mark -m "${ED%/}"/opt/slack/slack
            }

wezterm:
  generator: builtin-github
  defaults:
    category: x11-terms
    template: ../../templates/simple.tmpl
    files_dir: '{{ .Values.pn }}'
    github:
      user: wezterm
      query: releases
      num_pages: 3

  extensions_defs:
    git-submodules:
      opts:
    rust:
      opts:
        crates_git_depth: 100
  packages:

    - wezterm:
        extensions:
          - rust
          # NOTE: keep this extension after rust
          - git-submodules
        transform:
          - kind: string
            match: 'Release '
            replace: ''
          - kind: regex
            match: '-.*'
            replace: ''
        vars:
          desc: A GPU-accelerated cross-platform terminal emulator and multiplexer written by @wez and implemented in Rust
          homepage: https://github.com/wezterm/wezterm
          license: Apache-2.0 Boost-1.0 BSD BSD-2 CC0-1.0 ISC LGPL-3+ MIT Apache-2.0 Unlicense ZLIB
          iuse: wayland +X
          required_use: "|| ( wayland X )"
          patches:
            - wezterm-rust-1.85.patch
          inherit:
            - bash-completion-r1
            - cargo
            - desktop
          rdepend: |
            dev-libs/openssl
            media-libs/fontconfig
            media-libs/mesa[X?,wayland?]
            x11-libs/libxkbcommon[X,wayland?]
            sys-apps/dbus
            wayland? ( dev-libs/wayland )
            X? (
                x11-themes/hicolor-icon-theme
                x11-libs/libX11
                x11-libs/libxkbcommon
                x11-libs/libxcb:=[xkb]
                x11-libs/xcb-util
                x11-libs/xcb-util-image
                x11-libs/xcb-util-keysyms
                x11-libs/xcb-util-wm
                x11-themes/xcursor-themes
            )
          bdepend: |
            dev-util/cmake
            dev-vcs/git
            virtual/pkgconfig
            virtual/rust
          depend: ${RDEPEND}
          extra_envs:
            - 'QA_FLAGS_IGNORED="usr/bin/.*"'
          body: |
            src_unpack() {
              cargo_src_unpack
              rm -rf ${S}
              mv ${WORKDIR}/{{ .Values.github_repo }}-* ${S} || die
            }
            # https://wezfurlong.org/wezterm/install/source.html
            src_configure() {
              if use X ; then
                cargo_src_configure --no-default-features --features vendored-fonts
              fi
            }
            src_install() {
              exeinto /usr/bin
              doexe target/release/wezterm
              doexe target/release/wezterm-gui
              doexe target/release/wezterm-mux-server
              doexe target/release/strip-ansi-escapes

              newbashcomp assets/shell-completion/bash wezterm

              insinto /usr/share/fish/vendor_completions.d/
              doins assets/shell-completion/fish

              insinto /usr/share/zsh/site-functions
              doins assets/shell-completion/zsh

              newmenu assets/wezterm.desktop org.wezfurlong.wezterm.desktop
              newicon assets/icon/wezterm-icon.svg org.wezfurlong.wezterm.svg

              insinto /usr/share/metainfo
              newins assets/wezterm.appdata.xml org.wezfurlong.wezterm.appdata.xml
            }
            pkg_postinst() {
              xdg_icon_cache_update
            }
            pkg_postrm() {
              xdg_icon_cache_update
            }


zoom:
  generator: custom
  generator_opts:
    script: ./custom-generators/zoom.sh
    enable_set_version: "false"
  defaults:
    template: ../../templates/simple.tmpl
    files_dir: '{{ .Values.pn }}'
    category: net-im
    assets:
      - name: '{{ .Values.pn | replace "-bin" "" }}-{{ .Values.version }}_x86_64.pkg.tar.xz'
        url: 'https://cdn.zoom.us/prod/{{ .Values.version }}/zoom_x86_64.pkg.tar.xz'

  packages:
    - zoom-bin:

        vars:
          desc: Video conferencing and web conferencing service
          homepage: https://zoom.us
          license: ZOOM
          restrict: strip preserve-libs
          iuse: pulseaudio
          s: '${WORKDIR}'

          inherit:
            - unpacker
            - xdg
          extra_envs:
            - 'QA_PREBUILT="opt/zoom/*"'
          rdepend: |
            app-crypt/mit-krb5
            pulseaudio? ( media-sound/pulseaudio )
            app-i18n/ibus
            dev-libs/glib:2
            dev-libs/libxslt
            dev-libs/nss
            media-libs/fontconfig
            media-libs/mesa
            sys-apps/dbus
            x11-libs/libSM
            x11-libs/libX11
            x11-libs/libXcomposite
            x11-libs/libXfixes
            x11-libs/libXi
            x11-libs/libXrandr
            x11-libs/libXrender
            x11-libs/libXtst
            x11-libs/libxcb
            x11-libs/libxshmfence
            x11-libs/xcb-util-image
            x11-libs/xcb-util-keysyms
          depend: |
            app-admin/chrpath
          body: |
            src_prepare() {
              rm -f ${WORKDIR}/.PKGINFO ${WORKDIR}/.INSTALL ${WORKDIR}/.MTREE
              rmdir usr/share/doc/zoom usr/share/doc
              sed -i \
                -e 's:Icon=Zoom.png:Icon=Zoom:' \
                -e 's:Application;::' \
                -e 's:/usr/bin/zoom:&-bin:' \
                "${WORKDIR}/usr/share/applications/Zoom.desktop"
              chrpath -r '' opt/zoom/platforminputcontexts/libfcitxplatforminputcontextplugin.so
              scanelf -Xr opt/zoom/platforminputcontexts/libfcitxplatforminputcontextplugin.so
              chrpath -r '' opt/zoom/libturbojpeg.so
              scanelf -Xr opt/zoom/libturbojpeg.so
              eapply_user
            }
            src_install() {
              rm "${S}"/usr/bin/zoom
              cp -Rp "${S}/"* "${D}"
              dosym ../../opt/zoom/ZoomLauncher /usr/bin/zoom-bin
              # Zoom needs the SUID bit set on chrome-sandbox, but the installer doesn't do that
              fperms 4755 /opt/zoom/cef/chrome_sandbox
            }
            pkg_preinst() {
              xdg_pkg_preinst
            }
            pkg_postinst() {
              xdg_desktop_database_update
              xdg_mimeinfo_database_update
              xdg_icon_cache_update
            }
            pkg_postrm() {
              xdg_desktop_database_update
              xdg_mimeinfo_database_update
              xdg_icon_cache_update
            }
