sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "dev-kit"
  url: "https://github.com/macaroni-os/dev-kit"
  branch: "mark-testing"

- name: "gnome-kit"
  url: "https://github.com/macaroni-os/gnome-kit"
  branch: "mark-testing"

- name: "desktop-kit"
  url: "https://github.com/macaroni-os/desktop-kit"
  branch: "mark-testing"

- name: "core-gl-kit"
  url: "https://github.com/macaroni-os/core-gl-kit"
  branch: "mark-testing"

- name: "media-kit"
  url: "https://github.com/macaroni-os/media-kit"
  branch: "mark-testing"

- name: "geaaru-kit"
  url: "https://github.com/geaaru/geaaru_overlay"
  branch: "funtoo"

target:
  name: xorg-kit
  url: "https://github.com/macaroni-os/xorg-kit"
  branch: mark-unstable

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: x11-libs/libfakekey
    - pkg: x11-libs/libvdpau
    - pkg: x11-libs/libwnck

    - pkg: x11-libs/mx
    - pkg: x11-libs/startup-notification
    - pkg: x11-libs/xapps

    # TODO: This library seems deprecated. We need to investigate
    - pkg: x11-libs/libcryptui
    # upstream archived. Keep this for old GPU
    - pkg: x11-libs/libva-intel-driver
    - pkg: x11-libs/libva-vdpau-driver
    # upstream archived. candidate for removal
    - pkg: x11-libs/libxklavier

    - pkg: x11-themes/sound-theme-freedesktop
    - pkg: x11-themes/xcursor-themes

    - pkg: media-libs/t1lib

    - pkg: virtual/jpeg
    - pkg: virtual/jpeg-compat
    - pkg: virtual/glu
    - pkg: virtual/opengl
    - pkg: virtual/freedesktop-icon-theme
