sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-unstable"

- name: "dev-kit"
  url: "https://github.com/macaroni-os/dev-kit"
  branch: "mark-unstable"

- name: "gnome-kit"
  url: "https://github.com/macaroni-os/gnome-kit"
  branch: "mark-unstable"

- name: "desktop-kit"
  url: "https://github.com/macaroni-os/desktop-kit"
  branch: "mark-unstable"

- name: "geaaru-kit"
  url: "https://github.com/geaaru/geaaru_overlay"
  branch: "funtoo"

- name: "media-kit"
  url: "https://github.com/macaroni-os/media-kit"
  branch: "mark-unstable"

- name: "core-gl-kit"
  url: "https://github.com/macaroni-os/core-gl-kit"
  branch: "mark-unstable"

- name: "xorg-kit"
  url: "https://github.com/macaroni-os/xorg-kit"
  branch: "mark-unstable"


target:
  name: xorg-kit
  url: "https://github.com/macaroni-os/xorg-kit"
  branch: mark-xl

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: dev-libs/glib:2
    - pkg: dev-libs/gobject-introspection
    - pkg: dev-libs/gobject-introspection-common

    - pkg: dev-util/gdbus-codegen
    - pkg: dev-util/glib-utils
    - pkg: dev-util/desktop-file-utils

    - pkg: x11-apps/mkfontdir
    - pkg: x11-apps/mkfontscale
    - pkg: x11-apps/bdftopcf
    - pkg: x11-apps/xauth
    - pkg: x11-apps/xprop
    - pkg: x11-apps/xset

    - pkg: x11-base/xcb-proto
    - pkg: x11-base/xorg-proto

    - pkg: x11-libs/cairo
    - pkg: x11-libs/fltk
    - pkg: x11-libs/libX11
    - pkg: x11-libs/libXau
    - pkg: x11-libs/libXdmcp
    - pkg: x11-libs/libXext
    - pkg: x11-libs/libXrender
    - pkg: x11-libs/libfontenc
    - pkg: x11-libs/libxcb
    - pkg: x11-libs/libICE
    - pkg: x11-libs/libSM
    - pkg: x11-libs/libXcomposite
    - pkg: x11-libs/libXdamage
    - pkg: x11-libs/libXfixes
    - pkg: x11-libs/libXft
    - pkg: x11-libs/libXi
    - pkg: x11-libs/libXmu
    - pkg: x11-libs/libXrandr
    - pkg: x11-libs/libXt
    - pkg: x11-libs/libXtst
    - pkg: x11-libs/libXxf86vm
    - pkg: x11-libs/libdrm
    - pkg: x11-libs/libpciaccess
    - pkg: x11-libs/libxkbcommon
    - pkg: x11-libs/libxshmfence
    - pkg: x11-libs/pango
    - pkg: x11-libs/pixman
    - pkg: x11-libs/xtrans

    - pkg: x11-misc/compose-tables
    - pkg: x11-misc/imake
    - pkg: x11-misc/xdg-utils
    - pkg: x11-misc/xdg-user-dirs
    - pkg: x11-misc/xorg-cf-files
    - pkg: x11-misc/shared-mime-info
    - pkg: x11-misc/makedepend

    - pkg: x11-proto/dri2proto
    - pkg: x11-proto/glproto
    - pkg: x11-proto/xproto

    - pkg: virtual/ttf-fonts

    - pkg: media-fonts/encodings
    - pkg: media-fonts/font-util
    - pkg: media-fonts/font-adobe-100dpi
    - pkg: media-fonts/font-adobe-75dpi
    - pkg: media-fonts/font-adobe-utopia-100dpi
    - pkg: media-fonts/font-adobe-utopia-75dpi
    - pkg: media-fonts/font-adobe-utopia-type1
    - pkg: media-fonts/font-alias
    - pkg: media-fonts/liberation-fonts
    - pkg: media-fonts/noto-emoji
    - pkg: media-fonts/urw-fonts

    - pkg: media-libs/aalib
    - pkg: media-libs/alsa-lib
    - pkg: media-libs/alsa-topology-conf
    - pkg: media-libs/alsa-ucm-conf
    - pkg: media-libs/audiofile
    - pkg: media-libs/flac
    - pkg: media-libs/fontconfig:1.0
    - pkg: media-libs/freetype:2
    - pkg: media-libs/giflib
    - pkg: media-libs/glu
    - pkg: media-libs/harfbuzz
    - pkg: media-libs/libpng
    - pkg: media-libs/libogg
    - pkg: media-libs/libsdl
    - pkg: media-libs/libsdl2
    - pkg: media-libs/libsndfile
    - pkg: media-libs/libvorbis
    - pkg: media-libs/lcms:2
    - pkg: media-libs/openjpeg:2
    - pkg: media-libs/opus
    - pkg: media-libs/jbig2dec
    - pkg: media-libs/libglvnd
    - pkg: media-libs/libjpeg-turbo
    - pkg: media-libs/mesa
    - pkg: media-libs/speexdsp
    - pkg: media-libs/tiff

    - pkg: media-sound/pulseaudio

    - pkg: media-gfx/graphite2
    - pkg: media-gfx/qrencode
    - pkg: media-gfx/fontforge

    - pkg: virtual/jpeg
    - pkg: virtual/glu
    - pkg: virtual/opengl
