ollama:
  generator: builtin-github
  defaults:
    category: app-ai
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple-github.tmpl
    github:
      query: releases

  extensions_defs:
    golang:
      opts:

  packages:

    - docker-model:
        github:
          user: docker
          repo: model-runner
        extensions:
          - golang
        transform:
          - kind: string
            match: 'Docker Model Runner v'
            replace: ''
        vars:
          inherit:
            - go-module
          bdepend: |
            virtual/pkgconfig
            compress? ( app-arch/upx-bin )
          iuse: compress +runner
          body: |
            src_compile() {
              # Compile model-cli
              pushd cmd/cli >/dev/null
              local cli_ldflags=(
                "-X \"github.com/{{ .Values.github_user }}/{{ .Values.github_repo }}/cmd/cli/desktop.Version={{ .Values.version }}\""
              )
              local runner_ldflags=(
                "-X \"main.Version={{ .Values.version }}\""
              )
              go build \
                -ldflags "${cli_ldflags[*]}" \
                -o ../../{{ .Values.pn }} -v -x || die
              popd >/dev/null
              if use compress ; then
                upx --brute -1 {{ .Values.pn }} || die
              fi

              if use runner ; then
                go build \
                  -ldflags "${runner_ldflags[*]}" \
                  -o model-runner
              fi
            }
            src_install() {
              exeinto /usr/libexec/docker/cli-plugins
              doexe {{ .Values.pn }}
              dodoc README.md
              if use runner ; then
                dobin model-runner
              fi
            }

    - docker-agent:
        github:
          user: docker
        extensions:
          - golang
        vars:
          inherit:
            - go-module
          bdepend: |
            virtual/pkgconfig
            compress? ( app-arch/upx-bin )
          iuse: +compress
          body: |
            src_compile() {
              custom_ldflags=(
                "-X \"github.com/{{ .Values.github_user }}/{{ .Values.github_repo }}/pkg/version.Version={{ .Values.version }}\""
                "-X \"github.com/{{ .Values.github_user }}/{{ .Values.github_repo }}/pkg/version.Commit={{ .Values.sha }}\""
              )
              go build \
                -ldflags "${custom_ldflags[*]}" \
                -o {{ .Values.pn }} -v -x || die
              if use compress ; then
                upx --brute -1 {{ .Values.pn }} || die
              fi
            }
            src_install() {
              exeinto /usr/libexec/docker/cli-plugins
              doexe {{ .Values.pn }}
              dodoc README.md
            }

    - llama-cpp:
        github:
          #per_page: 5
          user: ggml-org
          repo: llama.cpp
          ignore_tags: true
        transform:
          - kind: regex
            match: "b"
            replace: "0.0."
        vars:
          inherit:
            - cmake
          nvidia_cuda_capability:
            - 120
            - 100
            - 87
            - 89
            - 75
            #- 61
            # Maybe we can use all directly.

          # cuda-native: Used to force local GPU identification
          iuse: static blas cuda vulkan cuda-native
          cdepend: |
            cuda? (
              dev-util/nvidia-cuda-toolkit
              dev-util/nvidia-nccl
            )
            vulkan? (
              dev-util/vulkan-tools
              media-libs/vulkan-layers
              media-libs/vulkan-loader
              media-libs/shaderc
              sci-libs/gsl
            )
            blas? (
              virtual/blas
              virtual/lapack
            )
          bdepend: |
            vulkan? (
              dev-util/vulkan-headers
            )
          depend: '${CDEPEND}'
          rdepend: '${CDEPEND}'
          body: |
            src_configure() {
              if use blas ; then
                # It seems that -lcblas -lblas is not injected. It's inject only -llapack
                export LDFLAGS="${LDFLAGS} -lcblas -lblas"
              fi
              export BUILD_COMMIT={{ .Values.sha }}

              local mycmakeargs=(
                -DBUILD_SHARED_LIBS=$(usex static OFF ON)
                -DGGML_CUDA=$(usex cuda ON OFF)
                -DGGML_BLAS=$(usex blas ON OFF)
                -DGGML_VULKAN=$(usex vulkan ON OFF)
                -DGGML_BLAS_VENDOR=Generic
                -DGGML_CUDA_ENABLE_UNIFIED_MEMORY=1
              )
              if use cuda-native ; then
                mycmakeargs+=(
                  -DCMAKE_CUDA_ARCHITECTURES=native
                )
              else
                mycmakeargs+=(
                  -DCMAKE_CUDA_ARCHITECTURES={{ .Values.nvidia_cuda_capability | join ";" }}
                )
              fi
              cmake_src_configure
            }
            src_install() {
              cmake_src_install
              dodoc README.md SECURITY.md CONTRIBUTING.md
            }


    - ollama:
        # TODO:
        # - improve integration with ROCm
        extensions:
          - golang
        vars:
          inherit:
            - go-module
            - cmake
            - user
          iuse: systemd clang cuda vulkan
          bdepend: |
            >=dev-lang/go-1.24
            clang? ( sys-devel/clang )
          rdepend: |
            vulkan? (
              media-libs/vulkan-loader
              media-libs/shaderc
            )
            cuda? (
              dev-util/nvidia-cuda-toolkit
            )
          depend: '${RDEPEND}'
          # It seems that trying to set this flags
          # breaks cmake. An upstream bug?
          #  -DGGML_CUDA=$(usex cuda ON OFF)
          #  -DGGML_VULKAN=$(usex vulkan ON OFF)
          body: |
            pkg_setup() {
              ebegin "Ensuring ollama user/group exist"
              enewgroup ollama
              enewuser ollama -1 -1 /var/lib/ollama ollama
            }
            src_configure() {
              local mycmakeargs=()
              if use clang ; then
                mycmakeargs+=(
                  -DCMAKE_C_COMPILER=clang
                  -DCMAKE_CXX_COMPILER=clang++
                )
              fi
              cmake_src_configure
            }
            src_prepare() {
              default
              go-module_src_prepare
              cmake_src_prepare
            }
            src_compile() {
              cmake_src_compile
              local ollama_ldflags=(
                 "-X github.com/ollama/ollama/version.Version=${PV}"
              )
              go build --ldflags "${ollama_ldflags[*]}" -mod=mod . || die "compile failed"
            }
            src_install() {
              cmake_src_install
              dobin {{ .Values.pn }}
              diropts -m0750 -o ollama -g ollama
              dodir /var/lib/ollama /var/lib/ollama/models/
              keepdir /var/lib/ollama/
              diropts
              dodoc README.md
              newconfd "${FILESDIR}"/ollama.confd ollama
              if use systemd ; then
                systemd_dounit "${FILESDIR}"/ollama.service
              else
                newinitd "${FILESDIR}"/ollama.initd ollama
              fi
              newenvd "${FILESDIR}"/ollama.envd "90ollama"
            }




