github_libs:
  generator: builtin-github

  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple-noindent-github.tmpl
    github:
      query: tags
  packages:
    - z3:
        category: sci-mathematics
        github:
          user: Z3Prover
        transform:
          - kind: string
            match: "{{ .Values.pn }}-"
            replace: ''
        vars:
          license: MIT
          python_compat: python3+
          inherit:
            - cmake
            - python-single-r1
            - toolchain-funcs
          slot: '0'
          iuse: doc examples gmp isabelle java openmp python
          required_use: '${PYTHON_REQUIRED_USE}'
          rdepend: |
            ${PYTHON_DEPS}
            gmp? ( dev-libs/gmp:= )
          depend: |
            ${RDEPEND}
            doc? ( app-doc/doxygen )
            java? ( virtual/jdk )
          extra_envs:
            - 'CMAKE_BUILD_TYPE=RelWithDebInfo'
          body: |
            pkg_setup() {
              python_setup
            }
            src_configure() {
              local mycmakeargs=(
                -DCMAKE_INSTALL_DOCDIR="${EPREFIX}/usr/share/doc/${P}"
                -DUSE_LIB_GMP=$(usex gmp)
                -DUSE_OPENMP=$(usex openmp)
                -DENABLE_EXAMPLE_TARGETS=OFF
                -DBUILD_DOCUMENTATION=$(usex doc)
                -DBUILD_PYTHON_BINDINGS=$(usex python)
                -DBUILD_JAVA_BINDINGS=$(usex java)
              )
              cmake_src_configure
            }
            src_install() {
            cmake_src_install
            dodoc README.md
            use examples && dodoc -r examples
            use python && python_optimize
            if use isabelle; then
            insinto /usr/share/Isabelle/contrib/${P}/etc
            newins - settings <<-EOF
            Z3_COMPONENT="\$COMPONENT"
            Z3_HOME="${EPREFIX}/usr/bin"
            Z3_SOLVER="${EPREFIX}/usr/bin/z3"
            Z3_REMOTE_SOLVER="z3"
            Z3_VERSION="${PV}"
            Z3_INSTALLED="yes"
            Z3_NON_COMMERCIAL="yes"
            EOF
            fi
            }
            pkg_postinst() {
            if use isabelle; then
            if [[ -f ${ROOT%/}/etc/isabelle/components ]]; then
            sed -e "/contrib\/${PN}-[0-9.]*/d" \
              -i "${ROOT%/}/etc/isabelle/components" || die
            cat <<-EOF >> "${ROOT%/}/etc/isabelle/components" || die
            contrib/${P}
            EOF
            fi
            fi
            }
            pkg_postrm() {
              if use isabelle; then
                if [[ ! ${REPLACING_VERSIONS} ]]; then
                  if [[ -f "${ROOT%/}/etc/isabelle/components" ]]; then
                    # Note: this sed should only match the version of this ebuild
                    # Which is what we want as we do not want to remove the line
                    # of a new Isabelle component being installed during an upgrade.
                    sed -e "/contrib\/${P}/d" \
                      -i "${ROOT%/}/etc/isabelle/components" || die
                  fi
                fi
              fi
            }

noop_pkgs:
  generator: builtin-noop

  defaults:
    template:  ../../templates/simple.tmpl
    category: sci-chemistry
    files_dir: "{{ .Values.pn }}"
    github:
      user: dleidert
      repo: chemical-mime
    vars:
      github_user: dleidert
      github_repo: chemical-mime
      versions:
        - '0.1.95_pre20171122'
      inherit:
        - autotools
        - xdg
      homepage: https://github.com/dleidert/chemical-mime
      desc: A collection of data files to add support for chemical MIME types
      git_sha: 4fd66e3b3b7d922555d1e25587908b036805c45b
      license: LGPL-2.1
      rdepend: |
        x11-misc/shared-mime-info
      depend: '${RDEPEND}'
      bdepend: |
        dev-libs/libxslt
        dev-util/intltool
        dev-util/desktop-file-utils
        virtual/pkgconfig
      body: |
        post_src_unpack() {
          mv {{ .Values.github_repo }}-* ${S}
        }
        src_prepare() {
          default
          # https://github.com/dleidert/chemical-mime/issues/4
          sed -i -e \
            '/<_comment/a\\t\t<generic-icon name="image-x-generic"/>' \
            src/chemical-mime-database.xml.in || die
          sed -i -e \
            's:acronym|alias|comment|:acronym|alias|comment|generic-icon|:' \
            xsl/cmd_freedesktop_org.xsl || die
          eautoreconf
        }
        src_configure() {
          econf \
            --disable-update-database \
            --without-gnome-mime \
            --without-kde-mime \
            --without-kde-magic
        }

    assets:
      - name: "{{ .Values.pn }}-{{ .Values.version }}-{{ substr 0 7 .Values.git_sha }}.tar.gz"
        url: https://github.com/dleidert/chemical-mime/archive/{{ .Values.git_sha }}.tar.gz

  packages:
    - chemical-mime-data:

gnuplot:
  generator: builtin-dirlisting

  defaults:
    files_dir: "{{ .Values.pn }}"
    category: sci-visualization
    template: ../../templates/simple.tmpl

    dir:
      url: https://sourceforge.net/projects/{{ .Values.pn }}/files/{{ .Values.pn }}/
      matcher: "files/{{ .Values.pn }}/[0-9]+(\\.[0-9]+)+/$"

    assets:
      - name: "{{ .Values.pn }}-{{ .Values.version }}.tar.gz"
        url: "https://download.sourceforge.net/{{ .Values.pn }}/{{ .Values.pn }}-{{ .Values.version }}.tar.gz"

    vars:
      desc: Command-line driven interactive plotting program
      homepage: http://www.gnuplot.info/
      license: gnuplot
      inherit:
        - autotools
        - toolchain-funcs
        - wxwidgets
      extra_envs:
        - 'WX_GTK_VER="3.0-gtk3"'
        - 'GP_VERSION="${PV%.*}"'
        - 'TEXMF="${EPREFIX}/usr/share/texmf-site"'
      iuse: bitmap cairo doc examples +gd gpic latex libcerf lua metafont metapost qt6 readline regis tgif wxwidgets X
      rdepend: |
        cairo? (
          x11-libs/cairo
          x11-libs/pango )
        gd? ( >=media-libs/gd-2.0.35-r3:2=[png] )
        latex? (
          virtual/latex-base
          lua? (
            dev-tex/pgf
            >=dev-texlive/texlive-latexrecommended-2008-r2 ) )
        libcerf? ( sci-libs/libcerf:= )
        lua? ( dev-lang/lua:0 )
        qt6? (
          dev-qt/qt5compat:6
          dev-qt/qtbase:6[gui]
          dev-qt/qtsvg:6 )
        readline? ( sys-libs/readline:0= )
        wxwidgets? (
          x11-libs/wxGTK:${WX_GTK_VER}=[X]
          x11-libs/cairo
          x11-libs/pango
          x11-libs/gtk+:3 )
        X? (
          x11-libs/libX11
          x11-libs/libXaw )
      depend: |
        ${RDEPEND}
        X? ( x11-base/xorg-proto )
      bdepend: |
        virtual/pkgconfig
        qt6? ( dev-qt/qttools:6[linguist] )
      body: |
        src_prepare() {
          default

          # Add special version identification as required by provision 2
          # of the gnuplot license
          sed -i -e "1s/.*/& (mark-macaroni revision ${PR})/" PATCHLEVEL || die

          eautoreconf

          # Make sure we don't mix build & host flags.
          sed -i \
            -e 's:@CPPFLAGS@:$(BUILD_CPPFLAGS):' \
            -e 's:@CFLAGS@:$(BUILD_CFLAGS):' \
            -e 's:@LDFLAGS@:$(BUILD_LDFLAGS):' \
            -e 's:@CC@:$(CC_FOR_BUILD):' \
            docs/Makefile.in || die
        }

        src_configure() {
          if ! use latex; then
            sed -i -e '/SUBDIRS/s/LaTeX//' share/Makefile.in || die
          fi

          use wxwidgets && setup-wxwidgets

          tc-export CC CXX
          tc-export_build_env BUILD_CC
          export CC_FOR_BUILD=${BUILD_CC}

          local myconf=(
            --with-texdir="${TEXMF}/tex/latex/${PN}"
            --with-readline=$(usex readline gnu builtin)
            $(use_with bitmap bitmap-terminals)
            $(use_with cairo)
            $(use_with gd)
            $(use_with gpic)
            $(use_with libcerf)
            $(use_with lua)
            $(use_with metafont)
            $(use_with metapost)
            $(use_with qt6 qt qt6)
            $(use_with regis)
            $(use_with tgif)
            $(use_with X x)
            --enable-stats
            $(use_enable wxwidgets)
            --without-amos
            --without-caca
            EMACS=no
          )

          econf "${myconf[@]}"
        }

        src_compile() {
          emake all
        }

        src_install() {
          emake DESTDIR="${D}" install

          dodoc BUGS NEWS PGPKEYS README* RELEASE_NOTES
          newdoc term/PostScript/README README-ps
          newdoc term/js/README README-js
          use lua && newdoc term/lua/README README-lua

          if use examples; then
            insinto /usr/share/${PN}/${GP_VERSION}
            doins -r demo
            rm "${ED}"/usr/share/${PN}/${GP_VERSION}/demo/{binary{1,2,3},dodecahedron.bin} || die
            rm "${ED}"/usr/share/${PN}/${GP_VERSION}/demo/plugin/*.{o,so} || die
          fi

          if use doc; then
            dodoc docs/gnuplot.pdf FAQ.pdf
            # Documentation for making PostScript files
            docinto psdoc
            dodoc docs/psdoc/{*.doc,*.tex,*.ps,*.gpi,README}
          fi
        }

        src_test() {
          emake check GNUTERM="dumb"
        }

        pkg_postinst() {
          use latex && texmf-update
        }

        pkg_postrm() {
          use latex && texmf-update
        }

  packages:
    - gnuplot:
