sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-unstable"

- name: "dev-kit"
  url: "https://github.com/macaroni-os/dev-kit"
  branch: "mark-testing"

- name: "games-kit"
  url: "https://github.com/macaroni-os/games-kit"
  branch: "mark-testing"

target:
  name: games-kit
  url: "https://github.com/macaroni-os/games-kit"
  branch: mark-unstable

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:
    - pkg: dev-games/freecell-solver

