net_vpn_dirlisting:
  generator: builtin-dirlisting
  template:
    engine: helm

  defaults:
    template: ../../templates/simple.tmpl
    category: net-vpn

  packages:
    - strongswan:
        template: templates/strongswan.tmpl
        dir:
          url: https://download.strongswan.org/
          matcher: "strongswan-.*.tar.bz2$"
        assets:
          - name: "{{ .Values.pn }}-{{ .Values.version }}.tar.bz2"
        transform:
          - kind: string
            match: 'strongswan-'
            replace: ''
          - kind: string
            match: '.tar.bz2'
            replace: ''
        vars:
          desc: IPsec-based VPN solution, supporting IKEv1/IKEv2 and MOBIKE
          homepage: https://www.strongswan.org/


net_dns_dirlisting:
  generator: builtin-dirlisting
  template:
    engine: helm

  defaults:
    files_dir: "{{ .Values.pn }}"
    category: net-dns

  packages:
    - unbound:
        template: templates/unbound.tmpl
        dir:
          url: https://nlnetlabs.nl/downloads/unbound/
          matcher: "unbound-1..*.tar.gz$"
          exclude: "rc"
        assets:
          - name: "{{ .Values.pn }}-{{ .Values.version }}.tar.gz"
        transform:
          - kind: string
            match: 'unbound-'
            replace: ''
          - kind: string
            match: '.tar.gz'
            replace: ''

net_wireless_noop:
  generator: builtin-noop
  template:
    engine: helm

  defaults:
    files_dir: "{{ .Values.pn }}"
    category: net-wireless

  packages:
    - wpa_supplicant:
        vars:
          versions:
            - "2.11"
        assets:
          - name: "{{ .Values.pn }}-{{ .Values.version }}.tar.gz"
            prefix: https://w1.fi/releases/
