net_vpn_dirlisting:
  generator: builtin-dirlisting
  template:
    engine: helm

  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: net-vpn

  packages:
    - strongswan:
        template: templates/strongswan.tmpl
        dir:
          url: https://download.strongswan.org/
          matcher: "strongswan-.*.tar.bz2$"
        assets:
          - name: "{{ .Values.pn }}-{{ .Values.version }}.tar.bz2"
        transform:
          - kind: string
            match: 'strongswan-'
            replace: ''
          - kind: string
            match: '.tar.bz2'
            replace: ''
        vars:
          desc: IPsec-based VPN solution, supporting IKEv1/IKEv2 and MOBIKE
          homepage: https://www.strongswan.org/

    - tor:
        dir:
          url: https://dist.torproject.org/
          exclude: "-alpha|-rc"
          matcher: "tor-.*.tar.gz$"
        transform:
          - kind: string
            match: 'tor-'
            replace: ''
          - kind: string
            match: '.tar.gz'
            replace: ''
        vars:
          inherit:
            - flag-o-matic
            - readme.gentoo-r1
            - user
          rdepend: |
            dev-libs/libevent[ssl]
            sys-libs/zlib
            caps? ( sys-libs/libcap )
            dev-libs/openssl
            lzma? ( app-arch/xz-utils )
            seccomp? ( sys-libs/libseccomp )
            zstd? ( app-arch/zstd )

          depend: |
            ${RDEPEND}
            app-text/asciidoc
          docs:
            - README.md
            - ChangeLog
            - ReleaseNotes
            - doc/HACKING
          iuse: caps lzma seccomp selinux tor-hardening zstd
          homepage: https://torproject.org
          desc: Anonymizing overlay network for TCP
          license: BSD GPL-2
          body: |
            pkg_setup() {
              enewgroup tor
              enewuser tor -1 -1 /var/lib/tor tor
            }
            src_configure() {
              export ac_cv_lib_cap_cap_init=$(usex caps)
              econf \
                --localstatedir="${EPREFIX}/var" \
                --enable-system-torrc \
                --enable-asciidoc \
                --disable-android \
                --disable-libfuzzer \
                --disable-module-dirauth \
                --enable-pic \
                --disable-rust \
                --disable-restart-debugging \
                --disable-zstd-advanced-apis  \
                --disable-unittests \
                --disable-coverage \
                --disable-libscrypt \
                $(use_enable lzma) \
                $(use_enable seccomp) \
                $(use_enable tor-hardening gcc-hardening) \
                $(use_enable tor-hardening linker-hardening) \
                $(use_enable zstd)
            }
            src_install() {
              default
              readme.gentoo_create_doc

              newconfd "${FILESDIR}"/tor.confd tor
              newinitd "${FILESDIR}"/tor.initd-r8 tor

              keepdir /var/lib/tor

              fperms 750 /var/lib/tor
              fowners tor:tor /var/lib/tor

              insinto /etc/tor/
              newins "${FILESDIR}"/torrc-r1 torrc
            }

net_dns_dirlisting:
  generator: builtin-dirlisting
  template:
    engine: helm

  defaults:
    files_dir: "{{ .Values.pn }}"
    category: net-dns

  packages:
    - unbound:
        template: templates/unbound.tmpl
        dir:
          url: https://nlnetlabs.nl/downloads/unbound/
          matcher: "unbound-1..*.tar.gz$"
          exclude: "rc"
        assets:
          - name: "{{ .Values.pn }}-{{ .Values.version }}.tar.gz"
        transform:
          - kind: string
            match: 'unbound-'
            replace: ''
          - kind: string
            match: '.tar.gz'
            replace: ''


bind_dirlisting:
  generator: builtin-dirlisting

  defaults:
    files_dir: "{{ .Values.pn }}"
    category: net-dns
    vars:
      python_compat: python3+
      tar_prefix: "bind"
    dir:
      url: https://downloads.isc.org/isc/bind9/
      matcher: '9.*'
      exclude: 'rc|W|P|ESV|a|b'
    assets:
      - name: "{{ .Values.tar_prefix }}-{{ .Values.version }}.tar.xz"
        prefix: "{{ .Values.version }}/"

  packages:
    - bind:
    - bind-tools:


net_wireless_noop:
  generator: builtin-noop
  template:
    engine: helm

  defaults:
    files_dir: "{{ .Values.pn }}"
    category: net-wireless

  packages:
    - wpa_supplicant:
        vars:
          versions:
            - "2.11"
        assets:
          - name: "{{ .Values.pn }}-{{ .Values.version }}.tar.gz"
            prefix: https://w1.fi/releases/

net_libs_github:
  generator: builtin-github
  defaults:
    category: net-libs
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple-github.tmpl
    github:
      query: tags

  packages:
    - libqmi:
        github:
          user: linux-mobile-broadband
        exclude:
          - '-dev|-rc'
        vars:
          desc: "Qualcomm MSM (Mobile Station Modem) Interface (QMI) modem protocol library"
          homepage: https://www.freedesktop.org/wiki/Software/libqmi/ https://gitlab.freedesktop.org/mobile-broadband/libqmi
          license: LGPL-2
          iuse: gtk-doc +mbim +qrtr
          inherit:
            - meson
          cdepend: |
            dev-libs/glib
            dev-libs/libgudev
            mbim? ( net-libs/libmbim )
            qrtr? ( net-libs/libqrtr-glib )
          depend: |
            ${CDEPEND}
          rdepend: |
            ${CDEPEND}
          bdepend: |
            app-shells/bash-completion
            virtual/pkgconfig
            gtk-doc? ( dev-util/gtk-doc )
          body: |
            src_configure() {
              local emesonargs=(
                $(meson_use qrtr)
                $(meson_use mbim mbim_qmux)
                $(meson_use gtk-doc gtk_doc)
                $(meson_use qrtr)
              )
              meson_src_configure
            }



