# Macaroni OS (MARK) Dracut Default parameters

dracutmodules="rescue resume bash kernel-modules rootfs-block udev-rules usrmount base fs-lib shutdown terminfo crypt lvm mdraid shutdown"

add_drivers+=" dm_mod dm_crypt "

omit_dracutmodules="fcoe"

# Quiet messages: failed to execute '/usr/lib/elogind/elogind-uaccess-command' '/usr/lib/elogind/elogind-uaccess-command /dev/dri/card0 ': No such file or directory
install_items+=" /usr/lib/elogind/elogind /usr/lib/elogind/elogind-cgroups-agent /usr/lib/elogind/elogind-uaccess-command /usr/lib/elogind/elogind-userdbd /usr/lib/elogind/elogind-userwork "
