# Macaroni OS (MARK) Dracut Default parameters

dracutmodules="rescue resume bash kernel-modules rootfs-block udev-rules usrmount base fs-lib shutdown terminfo shutdown"

omit_dracutmodules="fcoe"

# Quiet messages: failed to execute '/lib64/elogind/elogind-uaccess-command' '/lib64/elogind/elogind-uaccess-command /dev/dri/card0 ': No such file or directory
install_items="/lib64/elogind/elogind-uaccess-command"
