pep517_standalone:
  generator: builtin-pypi

  defaults:
    category: dev-python
    template: "../../templates/pypi-generic-helm.tmpl"
    vars:
      du_pep517: standalone
    python_compat: "python3+"

  packages:

    - flit_core:
        pypi_name: flit_core

    - pdm-backend:
        pypi_name: pdm_backend
        pydeps:
          py:all:runtime:
            - packaging >= 24.0
            - editables
            - importlib_metadata
            - pyproject-metadata
            - tomli
            - tomli-w
          py:all:tool:
            - packaging >= 24.0
            - editables
            - importlib_metadata
            - pyproject-metadata
            - tomli
            - tomli-w
            - zipp
        vars:
          body: |
            src_prepare() {
                rm -r src/pdm/backend/_vendor || die
                find -name '*.py' -exec sed \
                    -e 's:from pdm\.backend\._vendor\.:from :' \
                    -e 's:from pdm\.backend\._vendor ::' \
                    -e 's:import pdm\.backend\._vendor\.:import :' \
                    -i {} + || die
                distutils-r1_src_prepare
            }

    - poetry-core:
        pypi_name: poetry_core
        pydeps:
          py:all:both:
            - attrs
            - jsonschema
            - lark
            - packaging
            - pyparsing
            - pyrsistent
            - six
            - tomlkit

setuptools:
  generator: builtin-pypi

  defaults:
    category: dev-python
    template: "../../templates/pypi-generic-helm.tmpl"
    vars:
      du_setuptools: no
    python_compat: "python3+"
    pydeps:
      py:all:post:
        - certifi >= 2016.9.26

  packages:
    - setuptools:
        vars:
          depend: |
            app-arch/unzip
          body: |
            SETUPTOOLS_USE_DISTUTILS=stdlib
            python_install() {
              export DISTRIBUTE_DISABLE_VERSIONED_EASY_INSTALL_SCRIPT=1
              distutils-r1_python_install
            }

hatchling_modules:
  generator: builtin-pypi

  defaults:
    category: dev-python
    template: "../../templates/pypi-generic-helm.tmpl"
    vars:
      du_pep517: hatchling

  packages:

    - hatch-vcs:
        pypi_name: hatch_vcs
        pydeps:
          py:all:both:
            - setuptools_scm

    - virtualenv:
        pydeps:
          py:all:tool:
            - hatch-vcs
          py:all:both:
            - distlib < 1
            - filelock < 4
            - platformdirs < 5
        python_compat: "python3+"
        vars:
          license: MIT


setuptools_modules:
  generator: builtin-pypi

  defaults:
    category: dev-python
    template: "../../templates/pypi-generic-helm.tmpl"
    vars:
      du_pep517: setuptools
    python_compat: "python3+"

  packages:
    - setuptools_scm_git_archive:
        pypi_name: setuptools_scm_git_archive
        vars:
          license: MIT
        pydeps:
          py:all:tool:
            - setuptools_scm

    - trove-classifiers:
        pypi_name: trove_classifiers
        pydeps:
          py:all:tool:
            - calver

maturin:
  generator: builtin-pypi
  extensions_defs:
    rust:
      opts:

  defaults:
    category: dev-util
    template: "../../templates/pypi-generic-helm.tmpl"
    python_compat: "python3+"
    extensions:
      - rust

  packages:
    - maturin:
        pydeps:
          py:all:tool:
            - setuptools-rust
          py:all:runtime:
            - tomli
        vars:
          inherit:
            - cargo
            - distutils-r1
          extra_envs:
            - 'ECARGO_BUNDLE_POSTFIX="mark-rust-bundle"'
            - 'CARGO_OPTIONAL="yes"'
          # setuptools-rust doesn't inject rust as dependency.
          # we need add this directly on bdepend.
          bdepend: |
            virtual/rust
          body: |
            src_unpack() {
              cargo_src_unpack
            }
            src_prepare() {
              distutils-r1_src_prepare
              # we build the Rust executable (just once) via cargo_src_compile
              sed -i -e '/setuptools_rust/d' -e '/rust_extensions/d' setup.py || die
            }
            src_configure() {
              export OPENSSL_NO_VENDOR=1
              export ZSTD_SYS_USE_PKG_CONFIG=1
              local myfeatures=(
                full
                password-storage
                native-tls
              )
              cargo_src_configure --no-default-features
            }
            src_compile() {
              cargo_src_compile
              distutils-r1_src_compile
            }
            src_install() {
              dobin target/release/maturin
              dodoc Changelog.md README.md
              local maturin=target/release/maturin
              mkdir -p "${D}"/usr/share/{bash-completion/completions/,fish/vendor_completions.d/,zsh/site-functions/} || die
              "${maturin}" completions bash > "${D}"/usr/share/bash-completion/${PN} || die
              "${maturin}" completions fish > "${D}"/usr/share/fish/vendor_completions.d//${PN}.fish || die
              "${maturin}" completions zsh > "${D}"/usr/share/zsh/site-functions/_${PN} || die
              distutils-r1_src_install
            }


