pep517_standalone:
  generator: builtin-pypi

  defaults:
    category: dev-python
    template: "../../templates/pypi-generic-helm.tmpl"
    vars:
      du_pep517: standalone
    python_compat: "python3+"

  packages:

    - flit_core:
        pypi_name: flit_core

    - pdm-backend:
        pypi_name: pdm_backend
        pydeps:
          py:all:runtime:
            - packaging >= 24.0
            - editables
            - importlib_metadata
            - pyproject-metadata
            - tomli
            - tomli-w
          py:all:tool:
            - packaging >= 24.0
            - editables
            - importlib_metadata
            - pyproject-metadata
            - tomli
            - tomli-w
        vars:
          body: |
            src_prepare() {
                rm -r src/pdm/backend/_vendor || die
                find -name '*.py' -exec sed \
                    -e 's:from pdm\.backend\._vendor\.:from :' \
                    -e 's:from pdm\.backend\._vendor ::' \
                    -e 's:import pdm\.backend\._vendor\.:import :' \
                    -i {} + || die
                distutils-r1_src_prepare
            }

    - poetry_core:
        pypi_name: poetry_core
        pydeps:
          py:all:both:
            - attrs
            - jsonschema
            - lark
            - packaging
            - pyparsing
            - pyrsistent
            - six
            - tomlkit

setuptools:
  generator: builtin-pypi

  defaults:
    category: dev-python
    template: "../../templates/pypi-generic-helm.tmpl"
    vars:
      du_setuptools: no
    python_compat: "python3+"
    pydeps:
      py:all:post:
        - certifi >= 2016.9.26

  packages:
    - setuptools:
        vars:
          depend: |
            app-arch/unzip
          body: |
            SETUPTOOLS_USE_DISTUTILS=stdlib
            python_install() {
              export DISTRIBUTE_DISABLE_VERSIONED_EASY_INSTALL_SCRIPT=1
              distutils-r1_python_install
            }

hatchling_modules:
  generator: builtin-pypi

  defaults:
    category: dev-python
    template: "../../templates/pypi-generic-helm.tmpl"
    vars:
      du_pep517: hatchling

  packages:
    - virtualenv:
        pydeps:
          py:all:tool:
            - hatch-vcs
          py:all:both:
            - distlib < 1
            - filelock < 4
            - platformdirs < 5
        python_compat: "python3+"
        vars:
          license: MIT


setuptools_modules:
  generator: builtin-pypi

  defaults:
    category: dev-python
    template: "../../templates/pypi-generic-helm.tmpl"
    vars:
      du_pep517: setuptools
    python_compat: "python3+"

  packages:
    - trove-classifiers:
        pypi_name: trove_classifiers
        pydeps:
          py:all:tool:
            - calver
