sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-i"

- name: "i18n-kit"
  url: "https://github.com/macaroni-os/i18n-kit"
  branch: "mark-iii"

target:
  name: i18n-kit
  url: "https://github.com/macaroni-os/i18n-kit"
  branch: mark-i

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

      - dir: ../../.github/workflows
        to: .github/workflows

      - file: ../../.goreleaser.yml
        to: .goreleaser.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: app-i18n/ibus
    - pkg: app-i18n/ibus-anthy
    - pkg: app-i18n/ibus-bambo
    - pkg: app-i18n/ibus-chewing
    - pkg: app-i18n/ibus-hangul
    - pkg: app-i18n/ibus-ime-backends
    - pkg: app-i18n/ibus-libpinyin
    - pkg: app-i18n/ibus-m17n
    - pkg: app-i18n/ibus-skk
    - pkg: app-i18n/ibus-rime
    - pkg: app-i18n/ibus-table
    - pkg: app-i18n/ibus-table-chinese
    - pkg: app-i18n/ibus-table-others
    - pkg: app-i18n/ibus-table-extraphrase
    - pkg: app-i18n/ibus-unikey
    - pkg: app-i18n/translate-shell
    - pkg: app-i18n/uchardet
    - pkg: app-i18n/unicode-cldr
    - pkg: app-i18n/unicode-data
