
linear_packages:
  generator: builtin-dirlisting

  defaults:
    template: ../../templates/simple.tmpl
    files_dir: "{{ .Values.pn }}"
    category: dev-libs


  packages:

    - liblinear:
        vars:
          license: BSD
          desc: A Library for Large Linear Classification
          homepage: https://www.csie.ntu.edu.tw/~cjlin/liblinear/ https://github.com/cjlin1/liblinear
          iuse: blas
          rdepend: |
            blas? ( virtual/blas )
          depend: |
            ${RDEPEND}
            blas? ( virtual/pkgconfig )
          inherit:
            - toolchain-funcs
          body: |
            src_prepare() {
              default
              sed -i \
                -e '/^CFLAGS/d;/^CXXFLAGS/d' \
                blas/Makefile || die
              sed -i \
                -e 's|make|$(MAKE)|g' \
                -e '/$(LIBS)/s|$(CFLAGS)|& $(LDFLAGS)|g' \
                -e '/^CFLAGS/d;/^CXXFLAGS/d' \
                -e 's|$(SHARED_LIB_FLAG)|& $(LDFLAGS)|g' \
                Makefile || die
            }
            src_compile() {
              emake \
                CC="$(tc-getCC)" \
                CXX="$(tc-getCXX)" \
                CFLAGS="${CFLAGS} -fPIC" \
                CXXFLAGS="${CXXFLAGS} -fPIC" \
                AR="$(tc-getAR)" \
                RANLIB="$(tc-getRANLIB)" \
                lib all
            }
            src_install() {
              dolib.so {{ .Values.pn }}.so.*
              dosym {{ .Values.pn }}.so.* /usr/$(get_libdir)/{{ .Values.pn }}$(get_libname)
              newbin predict {{ .Values.pn }}-predict
              newbin train {{ .Values.pn }}-train
              doheader linear.h
              dodoc README
            }

        dir:
          #https://www.csie.ntu.edu.tw/~cjlin/liblinear/liblinear-2.48.tar.gz
          url: https://www.csie.ntu.edu.tw/~cjlin/liblinear/
          matcher: "liblinear-.*.tar.gz$"
        transform:
          - kind: string
            match: "liblinear-"
            replace: ""
          - kind: string
            match: ".tar.gz"
            replace: ""


etcher:
  generator: builtin-github
  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: sys-boot
    github:
      query: releases
  packages:
    - etcher-bin:
        github:
          user: balena-io
          repo: etcher
        assets:
          - name: '{{ .Values.pn }}-{{ .Values.version }}.linux-amd64.tar.gz'
            matcher: 'balena-{{ .Values.pn | replace "-bin" "" }}_{{ .Values.version }}_amd64.deb$'
        vars:
          inherit:
            - desktop
            - eutils
            - electron
            - unpacker
            - pax-utils
            - xdg
          desc: Flash OS images to SD cards & USB drives, safely and easily.
          homepage: https://etcher.io/
          license: GPL-2
          cdepend: |
            media-libs/libpng
            x11-libs/gtk+
            x11-libs/cairo
            x11-libs/libXtst
            sys-apps/lsb-release
          depend: ${CDEPEND}
          rdepend: |
            ${CDEPEND}
            x11-libs/libnotify
            x11-libs/libXScrnSaver
            dev-libs/nss
          body: |
            src_unpack() {
              # etcher does not use a containing folder(deb archive)
              # manual intervention required
              install -d "${WORKDIR}/${P}"
              S="${WORKDIR}/${P}"
              cd "${S}" || die "cd into target directory ${S} failed"
              unpack_deb "${A}"
            }
            src_install() {
              local instdir="/opt/balenaEtcher"
              local balenabin="balena-{{ .Values.pn | replace "-bin" "" }}"
              insinto ${instdir}
              doins -r *
              dosym "${instdir}/${balenabin}" "/usr/bin/{{ .Values.pn | replace "-bin" "" }}" || die
              make_wrapper "{{ .Values.pn | replace "-bin" "" }}" "${instdir}/${balenabin}" || die
              # only contains changelog"
              rm -rf "${D}/usr/share/doc" || die
              # use own desktop file
              rm -fR "${D}/usr/share/applications" || die
              domenu "${FILESDIR}/{{ .Values.pn | replace "-bin" "" }}.desktop" || die
              # correct permissions of install components
              fperms a+x "${instdir}/usr/bin/${balenabin}" || die
              pax-mark m "${instdir}/usr/bin/${balenabin}" || die
            }
            pkg_postinst() {
              xdg_pkg_postinst
            }
            pkg_postrm() {
              xdg_pkg_postrm
            }

