sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-testing"

- name: "security-kit"
  url: "https://github.com/macaroni-os/security-kit"
  branch: "mark-testing"

target:
  name: kernel-kit
  url: "https://github.com/macaroni-os/kernel-kit"
  branch: mark-xl

  fixups:
    include:
      - file: ../../LICENSE.txt
        to: LICENSE.txt

  atoms_defaults:
    max_versions: 3

  atoms:
    - pkg: sys-kernel/linux-headers
      conditions:
        - '>=sys-kernel/linux-headers-6.9'
        - '<sys-kernel/linux-headers-6.10'

    - pkg: sys-kernel/linux-headers
      conditions:
        - '>=sys-kernel/linux-headers-5.10'
        - '<sys-kernel/linux-headers-5.11'

