linux_kernel_dirlisting:
  generator: builtin-dirlisting
  template:
    engine: helm

  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: sys-kernel

  packages:
    - linux-firmware:
        dir:
          url: https://mirrors.edge.kernel.org/pub/linux/kernel/firmware/
          matcher: 'linux-firmware-.*.tar.xz'
        transform:
          - kind: string
            match: 'linux-firmware-'
            replace: ''
          - kind: string
            match: '.tar.xz'
            replace: ''
        vars:
          desc: Linux firmware files
          homepage: https://git.kernel.org/?p=linux/kernel/git/firmware/linux-firmware.git
          license: GPL-2 GPL-2+ GPL-3 BSD MIT MPL-1.1 linux-fw-redistributable BSD-2 BSD-4 ISC no-source-code
          iuse: initramfs
          restrict: strip
          extra_envs:
            - 'QA_PREBUILT="*"'
          bdepend: |
            initramfs? ( app-arch/cpio ) app-misc/rdfind
          rdepend: |
            initramfs? ( !<=app-admin/ego-2.8.5 )
          patches:
            - linux-firmware-copy-firmware.patch
          body: |
            src_prepare() {
              default
              if use initramfs; then
                if [[ -d "${S}/amd-ucode" ]]; then
                  local UCODETMP="${T}/ucode_tmp"
                  local UCODEDIR="${UCODETMP}/kernel/x86/microcode"
                  mkdir -p "${UCODEDIR}" || die
                  echo 1 > "${UCODETMP}/early_cpio"
                  local amd_ucode_file="${UCODEDIR}/AuthenticAMD.bin"
                  cat "${S}"/amd-ucode/*.bin > "${amd_ucode_file}" || die "Failed to concat amd cpu ucode"
                  if [[ ! -s "${amd_ucode_file}" ]]; then
                    die "Sanity check failed: '${amd_ucode_file}' is empty!"
                  fi
                  pushd "${UCODETMP}" &>/dev/null || die
                  find . -print0 | cpio --quiet --null -o -H newc -R 0:0 > "${S}"/amd-uc.img
                  popd &>/dev/null || die
                  if [[ ! -s "${S}/amd-uc.img" ]]; then
                    die "Failed to create '${S}/amd-uc.img'!"
                  fi
                else
                  # If this will ever happen something has changed which
                  # must be reviewed
                  die "'${S}/amd-ucode' not found!"
                fi
              fi
              echo "# Remove files that shall not be installed from this list." > ${PN}.conf
              find * ! -type d ! \( -name ${PN}.conf -o -name amd-uc.img \) >> ${PN}.conf
            }
            src_install() {
              ./copy-firmware.sh -v "${ED}/lib/firmware" || die
              if use initramfs ; then
                insinto /lib/firmware/amd-ucode
                doins "${S}"/amd-uc.img
              fi
            }
            pkg_preinst() {
              # Make sure /boot is available if needed.
              use initramfs && ego_pkg_preinst
              # Fix 'symlink is blocked by a directory' Bug #871315 on Gentoo and FL-10491 on Funtoo
              if has_version "<${CATEGORY}/${PN}-20220913-r1" ; then
                rm -rf "${EROOT}"/lib/firmware/qcom/LENOVO/21BX*
              fi
            }
            pkg_postinst() {
              # Don't forget to umount /boot if it was previously mounted by us.
              use initramfs && ego_pkg_postinst
            }
            pkg_prerm() {
              # Make sure /boot is mounted so that we can remove /boot/amd-uc.img!
              use initramfs && ego_pkg_prerm
            }
            pkg_postrm() {
              # Don't forget to umount /boot if it was previously mounted by us.
              use initramfs && ego_pkg_postrm
            }

    - vanilla-headers:
        dir:
          url: https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/
          matcher: 'linux-.*.tar.xz'
        selector:
          - '>6.12'
          - '<6.13'
        transform:
          - kind: string
            match: 'linux-'
            replace: ''
          - kind: string
            match: '.tar.xz'
            replace: ''
        category: sys-kernel
        vars:
          depend: |
            !<sys-kernel/linux-headers-6.12
          bdepend: |
            app-arch/xz-utils
            dev-lang/perl
            net-misc/rsync
            !<sys-kernel/linux-headers-6.12
            !!sys-kernel/debian-headers
          desc: Linux kernel header files
          homepage: https://kernel.org
          inherit:
            - eutils
            - toolchain-funcs
          license: GPL-2
          patches:
            - 00_all_0002-x86-do-not-build-relocs-tool-when-installing-headers.patch
          restrict: binchecks strip
          s: '${WORKDIR}/linux-${PV}'
          body: |
            pkg_setup() {
              export REAL_ARCH="$ARCH"
              # will interfere with Makefile if set
              unset ARCH; unset LDFLAGS
            }
            src_prepare() {
              default
              # drop unused errno.h include
              sed -e '/^#include <errno.h>/d' -i ${S}/scripts/unifdef.c
            }
            src_compile() {
              :
            }
            src_install() {
              # fix permissions in source tree
              cd "${WORKDIR}"
              chown -R 0:0 * >& /dev/null
              chmod -R a+r-w+X,u+w *
              cd "${OLDPWD}"
              [[ -L /usr/include/linux ]] && { rm /usr/include/linux || die; }
              [[ -L /usr/include/asm ]] && { rm /usr/include/asm || die; }
              emake O="${D}" ARCH="$(tc-arch-kernel)" headers_install \
                || die "could not install headers to image"
              # prune non-headers from tree
              rm "${D}"/{arch,include,scripts} -r
              find "${D}" '(' -name '.install' -o -name '*.cmd' ')' -delete
            }

virtual_os_headers:
  generator: builtin-noop
  defaults:
    template: ../../templates/simple.tmpl
    files_dir: "{{ .Values.pn }}"
    ignore_artefacts: true
  packages:
    - linux-headers:
        revision: 1
        category: sys-kernel
        vars:
          depend: ${RDEPEND}
          desc: "Virtual for Linux kernel headers"
          homepage: https://kernel.org
          license: GPL-2
          rdepend: |
            !<sys-kernel/linux-headers-{{ addf .Values.version 0.01 }}
          pdepend: |
            || (
              >=sys-kernel/debian-headers-{{ .Values.version }}
              >=sys-kernel/vanilla-headers-{{ .Values.version }}
            )
          versions:
            - '6.12'

    - os-headers:
        category: virtual
        vars:
          desc: "Virtual for operating system headers"
          # Presently we only support Linux
          depend: ${RDEPEND}
          rdepend: |
            || (
              sys-kernel/debian-headers
              sys-kernel/vanilla-headers
            )
          versions:
            - '2'
