golang_forensics_github:
  generator: builtin-github
  defaults:
    category: app-forensics
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple-github.tmpl
    github:
      query: releases
    extensions:
      - golang
    vars:
      body: |
        src_compile() {
          {{- if .Values.go_build }}
          {{- .Values.go_build }}
          {{- else }}
          go build -mod=mod . || die "compile failed"
          {{- end }}
        }
        src_install() {
          {{- if .Values.new_bin }}
          newbin {{ .Values.binary }} {{ .Values.pn }}
          {{- else }}
          dobin {{ .Values.pn }}
          {{- end }}
          dodoc README.md
        }

  extensions_defs:
    golang:
      opts:

  packages:
    - gobuster:
        github:
          user: OJ
        vars:
          inherit:
            - go-module
          bdepend: |
            >=dev-lang/go-1.24

    - copyfail-go:
        github:
          user: badsectorlabs
        vars:
          new_bin: true
          binary: copyfail
          bdepend: |
            >=dev-lang/go-1.26.2
          inherit:
            - go-module

    - osv-scanner:
        github:
          user: google
        vars:
          bdepend: |
            >=dev-lang/go-1.26.2
          inherit:
            - go-module
          go_build: |
            go build -mod=mod ./cmd/osv-scanner || die "compile failed"
