golang_forensics_github:
  generator: builtin-github
  defaults:
    category: app-forensics
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple-github.tmpl
    github:
      query: releases
    vars:
      body: |
        src_compile() {
          go build -mod=mod . || die "compile failed"
        }
        src_install() {
          {{- if .Values.new_bin }}
          newbin {{ .Values.binary }} {{ .Values.pn }}
          {{- else }}
          dobin {{ .Values.pn }}
          {{- end }}
          dodoc README.md
        }

  extensions_defs:
    golang:
      opts:

  packages:
    - gobuster:
        extensions:
          - golang
        github:
          user: OJ
        vars:
          inherit:
            - go-module
          bdepend: |
            >=dev-lang/go-1.24

    - copyfail-go:
        extensions:
          - golang
        github:
          user: badsectorlabs
        vars:
          new_bin: true
          binary: copyfail
          bdepend: |
            >=dev-lang/go-1.26.2
          inherit:
            - go-module


