openssl:
  generator: builtin-github

  defaults:
    category: dev-libs
    files_dir: "{{ .Values.pn }}"
    github:
      query: releases

  packages:
    - openssl:
        template: templates/openssl3.tmpl
        github:
          user: openssl
          num_pages: 10
        vars:
          homepage: https://github.com/openssl/openssl
          desc: TLS/SSL and crypto library
          license: Apache-2.0
        # Uses 3.0 LTS release
        selector:
          - '<3.1.0'
          - '>3.0.0'
        transform:
          - kind: string
            match: 'OpenSSL '
            replace: ''

    - openssh:
        category: net-misc
        vars:
          keywords: "*"
        github:
          user: openssh
          repo: openssh-portable
          query: tags
        transform:
          - kind: string
            match: 'P'
            replace: 'p'
          - kind: string
            match: 'V_'
            replace: ''
          - kind: string
            match: '_'
            replace: '.'
          - kind: string
            match: '.p'
            replace: '_p'


sys_apps:
  generator: builtin-github

  defaults:
    category: sys-apps
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple-github.tmpl
    github:
      query: releases

  packages:

    - libxcrypt:
        category: sys-libs
        github:
          user: besser82
        vars:
          bdepend: |
            !!<sys-apps/man-pages-6.17
          rdepend: |
            >=sys-libs/glibc-2.41
          depend: '${RDEPEND}'
          inherit:
            - ltprune
          body: |
            src_configure() {
              ./autogen.sh
              # Do not install into /usr so that tcb and pam can use us.
              econf --libdir=/$(get_libdir) --disable-static
            }
            src_install() {
              default
              prune_libtool_files
            }

    - bubblewrap:
        github:
          user: containers
        vars:
          desc: Unprivileged sandboxing tool, namespaces-powered chroot-like solution
          homepage: https://github.com/containers/bubblewrap/
          license: LGPL-2
          iuse: selinux suid
          rdepend: |
            sys-libs/libseccomp
            sys-libs/libcap
            selinux? ( sys-libs/libselinux )
          depend: ${RDEPEND}
          bdepend: |
            app-text/docbook-xml-dtd:4.3
            app-text/docbook-xsl-stylesheets
            dev-libs/libxslt
            virtual/pkgconfig
          inherit:
            - meson

          body: |
            src_configure() {
              local emesonargs=(
                -Dbash_completion=enabled
                -Dman=enabled
                -Dtests=false
                -Dzsh_completion=enabled
                $(meson_feature selinux)
              )
              meson_src_configure
            }
            src_install() {
              meson_src_install
              if use suid; then
                chmod u+s "${ED}"/usr/bin/bwrap
              fi
            }

sys_auth_pkgs:
  generator: builtin-github
  defaults:
    category: sys-auth
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple-github.tmpl
    github:
      query: tags
  packages:

    - elogind:
        transform:
          - kind: string
            match: "V"
            replace: ""
        github:
          per_page: 100
          num_pages: 3
        vars:
          python_compat: python3+
          inherit:
            - meson
            - pam
            - udev
            - python-any-r1
            - xdg-utils
          iuse: +acl audit cgroup-hybrid debug doc +pam +policykit
          patches:
            - elogind-252.9-nodocs.patch
            - elogind-255.17-revert-s2idle.patch
            - elogind-255.22-revert-openrc-user.patch
          bdepend: |
            app-text/docbook-xml-dtd:4.2
            app-text/docbook-xml-dtd:4.5
            app-text/docbook-xsl-stylesheets
            dev-util/gperf
            dev-util/intltool
            virtual/pkgconfig
          rdepend: |
            audit? ( sys-process/audit )
            sys-apps/util-linux
            sys-libs/libcap
            virtual/libudev:=
            acl? ( sys-apps/acl )
            pam? ( sys-libs/pam )
            !sys-apps/systemd
          depend: '${RDEPEND}'
          pdepend: |
            sys-apps/dbus
            policykit? ( sys-auth/polkit )
          body: |
            src_prepare() {
              default
              xdg_environment_reset

              sed -e "s/#RemoveIPC=yes/RemoveIPC=no/" \
                -i src/login/logind.conf.in || die

            }
            src_configure() {
              if use cgroup-hybrid; then
                cgroupmode="hybrid"
              else
                cgroupmode="unified"
              fi

              python_setup

              EMESON_BUILDTYPE="$(usex debug debug release)"

              local emesonargs=(
                -Ddocdir="${EPREFIX}/usr/share/doc/${PF}"
                -Dhtmldir="${EPREFIX}/usr/share/doc/${PF}/html"
                -Dudevrulesdir="${EPREFIX}$(get_udevdir)"/rules.d
                --libexecdir="lib/elogind"
                --localstatedir="${EPREFIX}"/var
                -Dbashcompletiondir="${EPREFIX}/usr/share/bash-completion/completions"
                -Dman=auto
                -Dsmack=true
                -Dcgroup-controller=openrc
                -Ddefault-hierarchy=${cgroupmode}
                -Ddefault-kill-user-processes=false
                -Dacl=$(usex acl enabled disabled)
                -Daudit=$(usex audit enabled disabled)
                -Dhtml=$(usex doc auto disabled)
                -Dpam=$(usex pam enabled disabled)
                -Dpamlibdir="$(getpam_mod_dir)"
                -Dselinux=disabled
                -Dtests=false
                -Dutmp=true
                -Dmode=release
                -Dhalt-path="${EPREFIX}/sbin/halt"
                -Dkexec-path="${EPREFIX}/usr/sbin/kexec"
                -Dnologin-path="${EPREFIX}/sbin/nologin"
                -Dpoweroff-path="${EPREFIX}/sbin/poweroff"
                -Dreboot-path="${EPREFIX}/sbin/reboot"
              )

              meson_src_configure
            }
            src_install() {
              meson_src_install
              keepdir /var/lib/elogind
              newinitd "${FILESDIR}"/${PN}.init-r1 ${PN}
              newconfd "${FILESDIR}"/${PN}.conf ${PN}
            }
            pkg_postinst() {
              udev_reload
              local file files
              # find custom hooks excluding known (nvidia-drivers, sys-power/tlp)
              if [[ -d "${EROOT}"/$(get_libdir)/elogind/system-sleep ]]; then
                readarray -t files < <(find "${EROOT}"/$(get_libdir)/elogind/system-sleep/ \
                  -type f \( -not -iname ".keep_dir" -a \
                    -not -iname "nvidia" -a \
                    -not -iname "49-tlp-sleep" \) || die)
              fi
              if [[ ${#files[@]} -gt 0 ]]; then
                ewarn "*** Custom hooks in obsolete path detected ***"
                for file in "${files[@]}"; do
                  ewarn "    ${file}"
                done
                ewarn "Move these custom hooks to ${EROOT}/etc/elogind/system-sleep/ instead."
              fi
            }
            pkg_postrm() {
              udev_reload
            }

    - polkit:
        github:
          user: polkit-org
        vars:
          iuse: +elogind examples gtk +introspection kde pam
          inherit:
            - meson
            - pam
            - pax-utils
            - systemd
            - user
            - xdg-utils
          patches:
            - polkit-126-dbusmock.patch
            - polkit-126-elogind.patch
          rdepend: |
            dev-lang/duktape
            dev-libs/glib:2
            dev-libs/expat
            elogind? ( sys-auth/elogind )
            !elogind? ( sys-apps/systemd )
            pam? (
              sys-auth/pambase
              sys-libs/pam
            )
          depend: '${RDEPEND}'
          bdepend: |
            app-text/docbook-xml-dtd:4.1.2
            app-text/docbook-xsl-stylesheets
            dev-libs/gobject-introspection-common
            dev-libs/libxslt
            sys-devel/gettext
            virtual/pkgconfig
            introspection? ( dev-libs/gobject-introspection )
          pdepend: |
            gtk? ( || (
              gnome-extra/polkit-gnome
              lxde-base/lxsession
            ) )
            kde? ( kde-plasma/polkit-kde-agent )
          docs:
            - docs/TODO
            - HACKING.md
            - NEWS.md
            - README.md
          license: LGPL2+
          body: |
            pkg_setup() {
                local u=polkitd
                local g=polkitd
                local h=/var/lib/polkit-1
                enewgroup ${g}
                enewuser ${u} -1 -1 ${h} ${g}
                esethome ${u} ${h}
            }
            src_prepare() {
                default
                sed -i -e 's|unix-group:@PRIVILEGED_GROUP@|unix-user:@PRIVILEGED_GROUP@|' src/polkitbackend/*-default.rules.in || die
            }
            src_configure() {
                xdg_environment_reset
                local emesonargs=(
                    --localstatedir="${EPREFIX}"/var
                    -Dauthfw="$(usex pam pam shadow)"
                    -Dexamples=false
                    -Dgtk_doc=false
                    -Dman=true
                    -Dtests=false
                    -Dsession_tracking="$(usex elogind 'elogind' 'logind')"
                    -Dsystemdsystemunitdir="$(systemd_get_systemunitdir)"
                    $(meson_use introspection)
                    $(usex pam "-Dpam_module_dir=$(getpam_mod_dir)" '')
                )
                meson_src_configure
            }
            src_compile() {
                meson_src_compile
                # Required for polkitd on hardened/PaX due to spidermonkey's JIT
                pax-mark mr src/polkitbackend/.libs/polkitd test/polkitbackend/.libs/polkitbackendjsauthoritytest
            }
            src_install() {
                meson_src_install
                if use examples ; then
                    docinto examples
                    dodoc src/examples/{*.c,*.policy*}
                fi
                diropts -m 0700 -o polkitd
                keepdir /usr/share/polkit-1/rules.d
                fperms u+s /usr/bin/pkexec
                fperms u+s /usr/lib/polkit-1/polkit-agent-helper-1
            }
            pkg_postinst() {
                chmod 0700 "${EROOT}"/{etc,usr/share}/polkit-1/rules.d
                chown polkitd "${EROOT}"/{etc,usr/share}/polkit-1/rules.d
            }

gnome_apps:
  generator: builtin-dirlisting
  generator_opts:
    # Limit rate at 1reqs/sec
    rate_limiter: "1"

  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: app-crypt
    dir:
      url: https://download.gnome.org/sources/{{ .Values.pkgname | default .Values.pn }}/{{ .Values.release }}/
      matcher: "{{ .Values.pkgname | default .Values.pn }}-.*.tar.xz$"
      exclude: 'rc|beta|alpha'
    transform:
      - kind: string
        match: "{{ .Values.pkgname | default .Values.pn }}-"
        replace: ""
      - kind: string
        match: ".tar.xz"
        replace: ""
    vars:
      license: LGPL-2.1
      homepage: 'https://gitlab.gnome.org/GNOME/{{ .Values.pkgname | default .Values.pn }}'

  packages:
    - gcr:
        selector:
          - '>4.0'
        vars:
          slot: '4'
          release: '4.4'
          desc: Libraries for cryptographic UIs and accessing PKCS#11 modules
          license: 'GPL-2 LGPL-2+'
          iuse: gnutls gtk gtk-doc +introspection systemd +vala
          required_use: |
            gtk-doc? ( introspection )
            vala? ( introspection )
          rdepend: |
            dev-libs/glib:2
            !gnutls? ( dev-libs/libgcrypt:0= )
            gnutls? ( net-libs/gnutls:0 )
            app-crypt/p11-kit
            app-crypt/libsecret
            systemd? ( sys-apps/systemd:= )
            gtk? ( x11-libs/gtk:4[introspection?] )
            sys-apps/dbus
            introspection? ( dev-libs/gobject-introspection:= )
          depend: '${RDEPEND}'
          bdepend: |
            gtk? ( dev-libs/libxml2:2 )
            dev-util/gdbus-codegen
            gtk-doc? ( dev-util/gi-docgen )
            sys-devel/gettext
            virtual/pkgconfig
            vala? ( $(vala_depend) )
          inherit:
            - flag-o-matic
            - gnome3
            - meson
            - vala
          body: |
            src_prepare() {
              default
              use vala && vala_src_prepare
              gnome3_environment_reset
            }
            src_configure() {
              filter-lto # https://gitlab.gnome.org/GNOME/gcr/-/issues/43
              local emesonargs=(
                  $(meson_use introspection)
                  $(meson_use gtk gtk4)
                  $(meson_use gtk-doc gtk_doc)
                  $(meson_feature systemd)
                  $(meson_use vala vapi)
                  -Dgpg_path="${EPREFIX}"/usr/bin/gpg
                  -Dssh_agent=true
              )
              if use gnutls; then
                  emesonargs+=( -Dcrypto=gnutls )
              else
                  emesonargs+=( -Dcrypto=libgcrypt )
              fi
              meson_src_configure
            }
            src_install() {
              meson_src_install
              if use gtk-doc; then
                  mkdir -p "${ED}"/usr/share/gtk-doc/html/ || die
                  mv "${ED}"/usr/share/doc/{gck-2,gcr-4} "${ED}"/usr/share/gtk-doc/html/ || die
              fi
            }
            pkg_postinst() {
              gnome3_pkg_postinst
            }
            pkg_postrm() {
              gnome3_pkg_postrm
            }

    # ATM gcr:3 is needed for seahorse until new seahorse with GTK4
    #     will be available.
    - gcr:
        selector:
          - '<4.0'
        vars:
          release: '3.41'
          desc: Libraries for cryptographic UIs and accessing PKCS#11 modules
          license: 'GPL-2 LGPL-2+'
          iuse: gtk gtk-doc +introspection systemd +vala
          required_use: |
            gtk-doc? ( introspection )
            vala? ( introspection )
          rdepend: |
            dev-libs/glib:2
            dev-libs/libgcrypt:0=
            app-crypt/p11-kit
            app-crypt/libsecret
            systemd? ( sys-apps/systemd:= )
            gtk? ( x11-libs/gtk+:3[introspection?] )
            sys-apps/dbus
            introspection? ( dev-libs/gobject-introspection:= )
          depend: '${RDEPEND}'
          bdepend: |
            gtk? ( dev-libs/libxml2:2 )
            dev-util/gdbus-codegen
            gtk-doc? ( dev-util/gi-docgen )
            sys-devel/gettext
            virtual/pkgconfig
            vala? ( $(vala_depend) )
          inherit:
            - flag-o-matic
            - gnome3
            - meson
            - vala
          body: |
            src_prepare() {
              default
              use vala && vala_src_prepare
              gnome3_environment_reset
            }
            src_configure() {
              filter-lto # https://gitlab.gnome.org/GNOME/gcr/-/issues/43
              local emesonargs=(
                  $(meson_use introspection)
                  $(meson_use gtk)
                  $(meson_use gtk-doc gtk_doc)
                  $(meson_feature systemd)
                  -Dgpg_path="${EPREFIX}"/usr/bin/gpg
                  -Dssh_agent=true
              )
              meson_src_configure
            }
            src_install() {
              meson_src_install
              # Drop files available on gcr:4
              rm "${ED}"/usr/libexec/gcr-ssh-agent
              if use systemd ; then
                rm "${ED}"/usr/lib/systemd/user/gcr-ssh-agent.{service,socket}
              fi
              if use gtk-doc; then
                  mkdir -p "${ED}"/usr/share/gtk-doc/html/ || die
                  mv "${ED}"/usr/share/doc/{gck-2,gcr-4} "${ED}"/usr/share/gtk-doc/html/ || die
              fi
            }
            pkg_postinst() {
              gnome3_pkg_postinst
            }
            pkg_postrm() {
              gnome3_pkg_postrm
            }

pax_utils:
  generator: builtin-dirlisting
  generator_opts:
    # Limit rate at 1reqs/sec
    rate_limiter: "1"

  defaults:
    files_dir: "{{ .Values.pn }}"
    template: ../../templates/simple.tmpl
    category: app-misc
    dir:
      url: https://dev.gentoo.org/~floppym/dist/
      matcher: "{{ .Values.pn }}-.*.tar.xz$"
    selector:
      - '>1.3.3'
    transform:
      - kind: string
        match: "{{ .Values.pn }}-"
        replace: ""
      - kind: string
        match: ".tar.xz"
        replace: ""
    vars:
      desc: ELF utils that can check files for security relevant properties
      homepage: 'https://wiki.gentoo.org/wiki/Hardened/PaX_Utilities'
      license: GPL-2
      bdepend: |
        caps? ( virtual/pkgconfig )
        man? ( app-text/xmlto )
      depend: '${RDEPEND}'
      rdepend: |
        caps? ( sys-libs/libcap )
        python? (
          ${PYTHON_DEPS}
          $(python_gen_cond_dep 'dev-python/pyelftools[${PYTHON_USEDEP}]')
        )
      inherit:
        - meson
        - python-single-r1
      iuse: caps man python seccomp
      python_compat: python3+
      required_use: |
        python? ( ${PYTHON_REQUIRED_USE} )
      body: |
        pkg_setup() {
          if use python; then
            python-single-r1_pkg_setup
          fi
        }
        src_configure() {
          local emesonargs=(
            "-Dlddtree_implementation=$(usex python python sh)"
            $(meson_feature caps use_libcap)
            $(meson_feature man build_manpages)
            $(meson_use seccomp use_seccomp)
            -Dtests=false
            # fuzzing is currently broken
            -Duse_fuzzing=false
          )
          meson_src_configure
        }
        src_install() {
          meson_src_install

          use python && python_fix_shebang "${ED}"/usr/bin/lddtree
        }

  packages:
    - pax-utils:
