sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-unstable"

- name: "net-kit"
  url: "https://github.com/macaroni-os/net-kit"
  branch: "mark-unstable"

target:
  name: net-kit
  url: "https://github.com/macaroni-os/net-kit"
  branch: mark-xl

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:
    - pkg: app-admin/sshguard
    - pkg: app-admin/ulogd

    - pkg: mail-client/alpine

    - pkg: mail-mta/postfix
    - pkg: mail-mta/ssmtp
    - pkg: mail-mta/nullmailer
    - pkg: mail-mta/sendmail

    - pkg: net-analyzer/arpwatch
    - pkg: net-analyzer/hping
    - pkg: net-analyzer/macchanger
    - pkg: net-analyzer/net-snmp
    - pkg: net-analyzer/nettop
    - pkg: net-analyzer/openbsd-netcat
    - pkg: net-analyzer/rrdtool
    - pkg: net-analyzer/fail2ban
    - pkg: net-analyzer/tcpflow
    - pkg: net-analyzer/tcpdump
    - pkg: net-analyzer/tcping
    - pkg: net-analyzer/tcptraceroute
    - pkg: net-analyzer/tcptrace
    - pkg: net-analyzer/tcpreplay
    - pkg: net-analyzer/traceroute
    - pkg: net-analyzer/nmap
    - pkg: net-analyzer/speedtest-cli

    - pkg: net-dialup/lrzsz
    - pkg: net-dialup/ppp
    - pkg: net-dialup/ppp-scripts
    - pkg: net-dialup/minicom

    - pkg: net-dns/avahi
    - pkg: net-dns/c-ares
    - pkg: net-dns/coredns
    - pkg: net-dns/dnsmasq
    - pkg: net-dns/dnssec-root
    - pkg: net-dns/libidn
    - pkg: net-dns/openresolv

    - pkg: net-firewall/arptables
    - pkg: net-firewall/conntrack-tools
    - pkg: net-firewall/ebtables
    - pkg: net-firewall/ipset
    - pkg: net-firewall/iptables
    - pkg: net-firewall/nftables
    - pkg: net-firewall/shorewall

    - pkg: net-fs/libnfs
    - pkg: net-fs/minio
    - pkg: net-fs/minio-client
    - pkg: net-fs/nfs-utils

    - pkg: net-ftp/atftp
    - pkg: net-ftp/ftpbase
    - pkg: net-ftp/proftpd

    - pkg: net-libs/libasyncns
    - pkg: net-libs/libesmtp
    - pkg: net-libs/libiscsi
    - pkg: net-libs/libmnl
    - pkg: net-libs/libndp
    - pkg: net-libs/libnet
    - pkg: net-libs/libnetfilter_acct
    - pkg: net-libs/libnetfilter_conntrack
    - pkg: net-libs/libnetfilter_cthelper
    - pkg: net-libs/libnetfilter_cttimeout
    - pkg: net-libs/libnetfilter_log
    - pkg: net-libs/libnetfilter_queue
    - pkg: net-libs/libnfnetlink
    - pkg: net-libs/libnftnl
    - pkg: net-libs/libnsl
    - pkg: net-libs/libpcap
    - pkg: net-libs/libpcapnav
    - pkg: net-libs/libslirp
    - pkg: net-libs/libssh
    - pkg: net-libs/libssh2
    - pkg: net-libs/libtirpc
    - pkg: net-libs/libtorrent
    - pkg: net-libs/rpcsvc-proto
    - pkg: net-libs/zeromq

    - pkg: net-mail/dovecot
    - pkg: net-mail/mailbase
    - pkg: net-mail/fetchmail
    - pkg: net-mail/getmail
    - pkg: net-mail/mailutils
    - pkg: net-mail/mailx

    - pkg: net-misc/bridge-utils
    - pkg: net-misc/dhcpcd
    - pkg: net-misc/dhcp
    - pkg: net-misc/ethertypes
    - pkg: net-misc/ifenslave
    - pkg: net-misc/iputils
    - pkg: net-misc/iperf:3
    - pkg: net-misc/ipcalc
    - pkg: net-misc/keychain
    - pkg: net-misc/networkmanager
    - pkg: net-misc/lksctp-tools
    - pkg: net-misc/rsync
    - pkg: net-misc/vconfig
    - pkg: net-misc/netkit-telnetd
    - pkg: net-misc/ntp
    - pkg: net-misc/olsrd
    - pkg: net-misc/openvswitch
    - pkg: net-misc/ovn
    - pkg: net-misc/radvd
    - pkg: net-misc/rclone
    - pkg: net-misc/socat
    - pkg: net-misc/sshpass
    - pkg: net-misc/stunnel
    - pkg: net-misc/tigervnc
    - pkg: net-misc/whois

    - pkg: net-nds/openldap
    - pkg: net-nds/rpcbind

    - pkg: net-p2p/rtorrent
    - pkg: net-p2p/syncthing

    - pkg: net-print/cups
    - pkg: net-print/cups-filters

    - pkg: net-proxy/cntlm
    - pkg: net-proxy/haproxy
    - pkg: net-proxy/privoxy
    - pkg: net-proxy/torsocks

    - pkg: net-vpn/openconnect
    - pkg: net-vpn/openfortivpn
    - pkg: net-vpn/openvpn
    - pkg: net-vpn/wireguard-tools
    - pkg: net-vpn/tailscale
    - pkg: net-vpn/vpnc

    - pkg: net-wireless/crda
    - pkg: net-wireless/iwd
    - pkg: net-wireless/wavemon
    - pkg: net-wireless/wepattack
    - pkg: net-wireless/wireless-regdb
    - pkg: net-wireless/wireless-tools
    - pkg: net-wireless/wpa_supplicant

    - pkg: sys-apps/iproute2
    - pkg: sys-apps/net-tools
    - pkg: sys-apps/ethtool
    - pkg: sys-apps/tcp-wrappers

    - pkg: www-apps/gitea
    - pkg: www-apps/gogs
    - pkg: www-apps/forgejo

    - pkg: virtual/mailx
    - pkg: virtual/mta
    - pkg: virtual/resolvconf

    # stable release 9.20
    - pkg: net-dns/bind
      conditions:
        - '<net-dns/bind-9.21.0'
    - pkg: net-dns/bind-tools
      conditions:
        - '<net-dns/bind-tools-9.21.0'
    # development release 9.21
    - pkg: net-dns/bind
      conditions:
        - '>=net-dns/bind-9.21.0'
        - '<net-dns/bind-9.22.0'
    - pkg: net-dns/bind-tools
      conditions:
        - '>=net-dns/bind-tools-9.21.0'
        - '<net-dns/bind-tools-9.22.0'
    - pkg: net-dns/unbound

    - pkg: net-vpn/strongswan
    - pkg: net-vpn/tor

