sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-iii"

- name: "lang-kit"
  url: "https://github.com/macaroni-os/lang-kit"
  branch: "mark-unstable"

target:
  name: lang-kit
  url: "https://github.com/macaroni-os/lang-kit"
  branch: mark-iii

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    # Julia
    # v12
    - pkg: dev-lang/julia-bin
      conditions:
        - '>=dev-lang/julia-bin-1.12.0'
        - '<dev-lang/julia-bin-1.13.0'

    # v10
    - pkg: dev-lang/julia-bin
      conditions:
        - '>=dev-lang/julia-bin-1.10.0'
        - '<dev-lang/julia-bin-1.11.0'

    - pkg: dev-lang/orc
    - pkg: dev-lang/swig
    - pkg: dev-lang/yasm
    - pkg: dev-lang/nasm

    - pkg: dev-lang/tcl:0
    - pkg: dev-lang/tk:0

    - pkg: dev-scheme/guile:12

    - pkg: dev-lang/duktape

    - pkg: net-libs/deno

    # Nodejs 14
    - pkg: net-libs/nodejs
      conditions:
        - '>=net-libs/nodejs-14.0.0'
        - '<net-libs/nodejs-15.0.0'

    # Nodejs 20
    - pkg: net-libs/nodejs
      conditions:
        - '>=net-libs/nodejs-20.0.0'
        - '<net-libs/nodejs-21.0.0'

    # Nodejs 22
    - pkg: net-libs/nodejs
      conditions:
        - '>=net-libs/nodejs-22.0.0'
        - '<net-libs/nodejs-23.0.0'

    # Nodejs 24
    - pkg: net-libs/nodejs
      conditions:
        - '>=net-libs/nodejs-24.0.0'
        - '<net-libs/nodejs-25.0.0'

    # Pascal
    - pkg: dev-lang/fpc
    - pkg: dev-lang/lazarus

    # Zig
    - pkg: dev-lang/zig
      conditions:
        - '<dev-lang/zig-0.16.0'
    - pkg: dev-lang/zig-bin
    - pkg: virtual/zig

    # Rust
    - pkg: dev-lang/rust-bin

    - pkg: virtual/rust

    - pkg: dev-lang/R

    - pkg: dev-lang/erlang

    - pkg: dev-tcltk/expect

    - pkg: dev-lang/lua
    - pkg: dev-lua/lua:5.3

    - pkg: dev-lua/lgi
    - pkg: dev-lua/lpeg
    - pkg: dev-lua/luaexpat
    - pkg: dev-lua/luajson
    - pkg: dev-lua/luasocket
    - pkg: dev-lua/LuaBitOp

    # Mono
    - pkg: dev-dotnet/libgdiplus
    - pkg: dev-lang/mono

    # Javascript
    - pkg: dev-lang/mujs

    - pkg: dev-lang/sassc

    # PHP
    - pkg: dev-lang/php:8.0
    - pkg: dev-lang/php:8.1
    - pkg: dev-lang/php:8.2
