sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-31"

- name: "browser-kit"
  url: "https://github.com/macaroni-os/browser-kit"
  branch: "mark-unstable"

target:
  name: browser-kit
  url: "https://github.com/macaroni-os/browser-kit"
  branch: mark-31

  fixups:
    include:
      - file: ../../LICENSE
        to: LICENSE

      - file: ../../.github/FUNDING.yml
        to: .github/FUNDING.yml

      - dir: ../../.github/workflows
        to: .github/workflows

      - file: ../../.goreleaser.yml
        to: .goreleaser.yml

  atoms_defaults:
    max_versions: 3

  atoms:

    - pkg: dev-lang/spidermonkey:78

    - pkg: www-client/brave-bin
    - pkg: www-client/firefox
#    - pkg: www-client/firefox-beta-bin
#    - pkg: www-client/firefox-bin
#    - pkg: www-client/google-chrome
#    - pkg: www-client/google-chrome-beta
#    - pkg: www-client/google-chrome-unstable
    - pkg: www-client/opera
#    - pkg: www-client/qutebrowser
#    - pkg: www-client/vivaldi
#    - pkg: www-client/vivaldi-snapshot
    - pkg: www-client/w3m

    - pkg: www-plugins/chrome-binary-plugins:beta
    - pkg: www-plugins/chrome-binary-plugins:stable
    - pkg: www-plugins/chrome-binary-plugins:unstable

    - pkg: virtual/w3m
